/* Cartographic Journey v9 — app logic */
(function(){
'use strict';
/* ---------------- DATA ---------------- */
const BOOKS = [
 {id:1, title:'달빛 아래 연등', orig:'Đèn Lồng Dưới Ánh Trăng', lang:'vi', country:'베트남', age:'child', isbn:'9791162341001', price:15000, pub:'Kim Đồng', year:2026, kdc:'833', pages:40, stock:'ok', new:true, color:['#7a2c1f','#c86a3c'], cur:[1,2,3], desc:'베트남 중추절 밤, 아이들이 손수 만든 등불을 들고 마을을 돌며 나누는 이야기. 한국어·베트남어 병기.'},
 {id:2, title:'우리 집 두 개의 설날', orig:'Two New Years at Home', lang:'en', country:'미국', age:'child', isbn:'9791162341002', price:16800, pub:'Candlewick', year:2026, kdc:'843', pages:36, stock:'ok', new:true, color:['#243a5a','#5a86b8'], cur:[1,3], desc:'한국계 미국인 가정이 음력설과 양력설을 함께 보내며 두 문화를 배우는 그림책.'},
 {id:3, title:'할머니의 아오자이', orig:'Chiếc Áo Dài Của Bà', lang:'vi', country:'베트남', age:'child', isbn:'9791162341003', price:14500, pub:'Nhã Nam', year:2025, kdc:'833', pages:44, stock:'ok', new:true, color:['#3c5a2a','#8fb46a'], cur:[1], desc:'베트남 전통 의상 아오자이에 담긴 세 세대 여성의 이야기.'},
 {id:4, title:'별을 세는 밤', orig:'数星星的夜晚', lang:'zh', country:'중국', age:'child', isbn:'9791162341004', price:15500, pub:'接力出版社', year:2026, kdc:'823', pages:32, stock:'wait', new:true, color:['#1f2c4a','#6b7fc4'], cur:[2], desc:'원소절 밤 등불을 띄우며 소원을 비는 소년의 이야기. 한중 이중언어.'},
 {id:5, title:'몽골 초원의 바람 아이', orig:'Салхины хүү', lang:'mn', country:'몽골', age:'teen', isbn:'9791162341005', price:13800, pub:'Монсудар', year:2025, kdc:'893', pages:120, stock:'ok', new:false, color:['#5a3a1f','#c9a86a'], cur:[2,3], desc:'유목민 가정의 소년이 도시 학교로 전학하며 겪는 성장 이야기.'},
 {id:6, title:'필리핀 할아버지의 바다 지도', orig:'Ang Mapa ng Dagat ni Lolo', lang:'tl', country:'필리핀', age:'child', isbn:'9791162341006', price:16000, pub:'Adarna House', year:2026, kdc:'899', pages:40, stock:'ok', new:true, color:['#0f4c5c','#3fa7b5'], cur:[1,2], desc:'섬나라 필리핀의 바다와 가족의 기억을 잇는 지도 이야기.'},
 {id:7, title:'다문화 가정 부모를 위한 첫 한국어 교실', orig:'Korean for Multicultural Parents', lang:'ko', country:'한국', age:'adult', isbn:'9791162341007', price:19000, pub:'한글샘', year:2025, kdc:'710', pages:220, stock:'ok', new:false, color:['#4a2a5a','#a67cc4'], cur:[3], desc:'학교 알림장, 병원, 관공서 등 생활 한국어 회화 중심 교재. 6개 언어 대역.'},
 {id:8, title:'태국의 물축제 송크란', orig:'สงกรานต์ของฉัน', lang:'th', country:'태국', age:'child', isbn:'9791162341008', price:15000, pub:'Nanmeebooks', year:2026, kdc:'899', pages:36, stock:'ok', new:true, color:['#7a1f4a','#d46aa0'], cur:[1,2], desc:'태국 새해 물축제 송크란을 통해 배우는 물과 가족의 의미.'},
 {id:9, title:'러시아 할머니의 마트료시카', orig:'Бабушкина матрёшка', lang:'ru', country:'러시아', age:'child', isbn:'9791162341009', price:16500, pub:'Самокат', year:2025, kdc:'892', pages:40, stock:'ok', new:false, color:['#8a1f1f','#e06060'], cur:[1], desc:'인형 속 인형처럼 이어지는 가족의 이야기.'},
 {id:10, title:'우즈베키스탄의 빵, 논', orig:'Non — O\'zbek noni', lang:'uz', country:'우즈베키스탄', age:'child', isbn:'9791162341010', price:14800, pub:'Yangi asr', year:2026, kdc:'899', pages:32, stock:'wait', new:true, color:['#8a5a1f','#e0a850'], cur:[2]},
 {id:11, title:'사서를 위한 다문화 장서 개발 가이드', orig:'Multicultural Collection Development', lang:'ko', country:'한국', age:'adult', isbn:'9791162341011', price:28000, pub:'도서관문화사', year:2026, kdc:'024', pages:310, stock:'ok', new:true, color:['#2a2a2a','#6a6a6a'], cur:[3], desc:'공공·학교도서관의 다문화 자료 선정 기준, 언어별 출판 시장, 서지 작성 실무.'},
 {id:12, title:'네팔 히말라야의 작은 학교', orig:'हिमालको सानो विद्यालय', lang:'ne', country:'네팔', age:'teen', isbn:'9791162341012', price:13500, pub:'Sajha', year:2025, kdc:'899', pages:96, stock:'ok', new:false, color:['#1f4a3a','#5ab08a'], cur:[2,3]},
 {id:13, title:'일본 여름 축제 마츠리', orig:'なつまつり', lang:'ja', country:'일본', age:'child', isbn:'9791162341013', price:15800, pub:'福音館', year:2026, kdc:'833', pages:32, stock:'ok', new:true, color:['#2f2f5a','#7c7cc4'], cur:[1,2]},
 {id:14, title:'인도네시아 그림자 인형극', orig:'Wayang Kulit', lang:'id', country:'인도네시아', age:'child', isbn:'9791162341014', price:16200, pub:'Gramedia', year:2025, kdc:'899', pages:44, stock:'ok', new:false, color:['#4a1f0f','#c07040'], cur:[1]},
];
const LANG_NAMES={ko:'한국어',en:'영어',vi:'베트남어',zh:'중국어',mn:'몽골어',tl:'필리핀어',th:'태국어',ru:'러시아어',uz:'우즈베크어',ne:'네팔어',ja:'일본어',id:'인도네시아어'};

const CURATIONS = [
 {id:1, type:'hall', titleKey:'c1_t', descKey:'c1_d'},
 {id:2, type:'stall', titleKey:'c2_t', descKey:'c2_d'},
 {id:3, type:'sky', titleKey:'c3_t', descKey:'c3_d'},
];

/* ---------------- I18N ---------------- */
const I18N = {
ko:{brand:'등불 도서관',brand_sub:'Lantern Night Library · 다문화 도서 납품',nav_home:'메인',nav_search:'도서 검색',nav_curation:'큐레이션',nav_cart:'견적함',
 hero_eyebrow:'2026 다문화 도서관 납품 전문 플랫폼',hero_title:'등불 아래<br>세계의 <em>이야기</em>가<br>모입니다',hero_desc:'12개 언어, 480개 출판사의 다문화 도서를 사서의 기준으로 검수해 납품합니다. 견적서 발급부터 서지 데이터(MARC) 제공까지 한 번에.',hero_cta1:'도서 검색·수서',hero_cta2:'등불 전시관 입장',stat_lang:'지원 언어',stat_books:'등록 도서',stat_lib:'납품 도서관',hero_hint:'마우스를 움직여 등불을 흔들어 보세요 · 클릭하면 불티가 날립니다',
 notice:'2026 하반기 공공도서관 다문화자료 구입 지원사업 납품 일정 안내 — 9월 말 견적 마감',notice_link:'견적서 발급하기',
 cur_eyebrow:'기획전 · Curated Exhibitions',cur_title:'등불처럼 걸어둔 이달의 기획전',cur_desc:'전시 형태가 각기 다른 세 개의 기획전. 3D 등불 전시관은 드래그해서 둘러볼 수 있습니다.',
 hall_eyebrow:'3D Lantern Hall',hall_desc:'드래그로 회랑을 돌려보고, 등불(표지)을 클릭하면 서지정보로 이동합니다.',
 new_eyebrow:'신간 · New Arrivals',new_title:'이번 달 입고 신간',view_active:'액티브',view_list:'서지 목록',
 lib1_t:'사서 검수 완료 도서',lib1_d:'현직 사서 12명이 내용·번역·제본 품질을 검수한 도서만 등록합니다.',lib2_t:'MARC/서지 데이터 제공',lib2_d:'납품 도서의 KORMARC 데이터와 장비 작업(라벨·바코드)을 함께 제공합니다.',lib3_t:'공문용 견적서 즉시 발급',lib3_d:'기관 할인율이 반영된 견적서를 PDF로 바로 출력해 기안에 첨부하세요.',
 search_eyebrow:'도서 검색 · 수서',search_title:'사서의 기준으로 찾는 다문화 도서',search_ph:'제목, 저자, ISBN',f_lang:'언어',f_age:'대상 연령',f_stock:'납품 상태',f_reset:'필터 초기화',sort_new:'최신 입고순',sort_price:'가격순',sort_title:'제목순',result_count:'{n}권',
 age_child:'유아·초등',age_teen:'청소년',age_adult:'성인·사서',stock_ok:'즉시 납품',stock_wait:'입고 대기',
 curpage_title:'기획전 전체 보기',type_hall:'3D 등불 전시관',type_stall:'야시장 가판대',type_sky:'하늘 등불',books_n:'{n}권 수록',
 c1_t:'세계 그림책 비엔날레 수상작',c1_d:'BIB·볼로냐 라가치 수상작 중 다문화 가정 아동을 위한 원서+번역서 세트.',c2_t:'아시아의 축제와 등불',c2_d:'연등회, 원소절, 송크란, 마츠리 — 축제로 배우는 이웃 나라 문화.',c3_t:'다문화 가정 부모·사서 필독서',c3_d:'생활 한국어, 장서 개발 가이드, 성장기 청소년 문학까지.',
 cart_eyebrow:'견적함 · Quotation Basket',cart_title:'납품 견적함',cart_summary:'견적 요약',cart_org:'기관 유형',org_public:'공공도서관 (12% 할인)',org_school:'학교도서관 (10% 할인)',org_multi:'다문화가족지원센터 (15% 할인)',org_personal:'개인 구매 (0%)',cart_sub:'정가 합계',cart_disc:'기관 할인',cart_total:'납품 예정 금액',cart_note:'부가세 면세(도서). 배송·장비작업비 별도 협의.',cart_quote:'공문용 견적서 발급',cart_clear:'견적함 비우기',cart_empty:'견적함이 비어 있습니다. 도서를 검색해 담아 주세요.',
 back:'목록으로',add:'견적함 담기',added:'견적함에 담았습니다',removed:'견적함에서 제거했습니다',cleared:'견적함을 비웠습니다',quote_done:'견적서(PDF) 발급 창을 엽니다',
 b_isbn:'ISBN',b_lang:'언어',b_country:'원산국',b_age:'대상',b_pub:'출판사',b_year:'출간',b_kdc:'KDC',b_pages:'쪽수',b_stock:'납품',price_unit:'원',qty:'수량',footer_desc:'다문화 도서관 납품 전문 · 사서와 함께 만드는 세계의 서가',th_title:'서명',th_lang:'언어',th_age:'대상',th_pub:'출판사',th_price:'정가',th_stock:'납품',th_act:''},
en:{brand:'Lantern Library',brand_sub:'Lantern Night Library · Multicultural book supply',nav_home:'Home',nav_search:'Search',nav_curation:'Curation',nav_cart:'Quote Basket',
 hero_eyebrow:'2026 Multicultural library supply platform',hero_title:'Under the lanterns,<br>the world\'s <em>stories</em><br>gather',hero_desc:'Multicultural books in 12 languages from 480 publishers, vetted by librarians. Quotation, MARC data and processing in one place.',hero_cta1:'Search & acquire',hero_cta2:'Enter Lantern Hall',stat_lang:'Languages',stat_books:'Titles',stat_lib:'Libraries served',hero_hint:'Move the mouse to sway the lanterns · click for sparks',
 notice:'2026 H2 public library multicultural collection grant — quotation deadline end of September',notice_link:'Issue a quotation',
 cur_eyebrow:'Curated Exhibitions',cur_title:'This month\'s exhibitions, hung like lanterns',cur_desc:'Three exhibitions in three display forms. Drag the 3D Lantern Hall to look around.',
 hall_eyebrow:'3D Lantern Hall',hall_desc:'Drag to rotate the gallery; click a lantern (cover) to open its record.',
 new_eyebrow:'New Arrivals',new_title:'Arrived this month',view_active:'Active',view_list:'Record list',
 lib1_t:'Librarian-vetted titles',lib1_d:'Only titles reviewed for content, translation and binding by 12 working librarians.',lib2_t:'MARC / bibliographic data',lib2_d:'KORMARC records plus labels and barcodes for every delivered title.',lib3_t:'Official quotation in seconds',lib3_d:'Print a PDF quotation with institutional discount applied, ready for approval.',
 search_eyebrow:'Search · Acquisition',search_title:'Find multicultural books by librarian criteria',search_ph:'Title, author, ISBN',f_lang:'Language',f_age:'Age group',f_stock:'Supply status',f_reset:'Reset filters',sort_new:'Newest',sort_price:'Price',sort_title:'Title',result_count:'{n} titles',
 age_child:'Children',age_teen:'Young adult',age_adult:'Adult · Librarian',stock_ok:'In stock',stock_wait:'Backorder',
 curpage_title:'All exhibitions',type_hall:'3D Lantern Hall',type_stall:'Night market stall',type_sky:'Sky lanterns',books_n:'{n} titles',
 c1_t:'Picture book biennale winners',c1_d:'BIB & Bologna Ragazzi winners as original + translation sets for multicultural children.',c2_t:'Festivals and lanterns of Asia',c2_d:'Yeondeunghoe, Lantern Festival, Songkran, Matsuri — neighbours through festivals.',c3_t:'Must-reads for parents & librarians',c3_d:'Everyday Korean, collection development guides, YA fiction.',
 cart_eyebrow:'Quotation Basket',cart_title:'Supply quotation basket',cart_summary:'Summary',cart_org:'Institution type',org_public:'Public library (12% off)',org_school:'School library (10% off)',org_multi:'Multicultural family center (15% off)',org_personal:'Personal (0%)',cart_sub:'List price total',cart_disc:'Institutional discount',cart_total:'Estimated total',cart_note:'Books are VAT-exempt. Shipping and processing quoted separately.',cart_quote:'Issue official quotation',cart_clear:'Clear basket',cart_empty:'Your basket is empty. Search and add titles.',
 back:'Back to list',add:'Add to basket',added:'Added to basket',removed:'Removed from basket',cleared:'Basket cleared',quote_done:'Opening quotation (PDF) print window',
 b_isbn:'ISBN',b_lang:'Language',b_country:'Origin',b_age:'Audience',b_pub:'Publisher',b_year:'Year',b_kdc:'KDC',b_pages:'Pages',b_stock:'Supply',price_unit:'KRW',qty:'Qty',footer_desc:'Multicultural library supply · building the world\'s shelves with librarians',th_title:'Title',th_lang:'Lang',th_age:'Audience',th_pub:'Publisher',th_price:'Price',th_stock:'Supply',th_act:''},
vi:{brand:'Thư viện Đèn Lồng',brand_sub:'Lantern Night Library · Cung ứng sách đa văn hóa',nav_home:'Trang chủ',nav_search:'Tìm sách',nav_curation:'Triển lãm',nav_cart:'Giỏ báo giá',
 hero_eyebrow:'Nền tảng cung ứng sách cho thư viện đa văn hóa 2026',hero_title:'Dưới ánh đèn lồng,<br><em>câu chuyện</em> của<br>thế giới hội tụ',hero_desc:'Sách đa văn hóa 12 ngôn ngữ từ 480 nhà xuất bản, được thủ thư thẩm định. Báo giá, dữ liệu MARC và xử lý kỹ thuật tại một nơi.',hero_cta1:'Tìm & bổ sung',hero_cta2:'Vào Sảnh Đèn Lồng',stat_lang:'Ngôn ngữ',stat_books:'Đầu sách',stat_lib:'Thư viện phục vụ',hero_hint:'Di chuột để làm đèn lồng đung đưa · nhấp để tóe lửa',
 notice:'Dự án hỗ trợ mua tài liệu đa văn hóa nửa cuối 2026 — hạn báo giá cuối tháng 9',notice_link:'Phát hành báo giá',
 cur_eyebrow:'Triển lãm tuyển chọn',cur_title:'Triển lãm tháng này, treo như đèn lồng',cur_desc:'Ba triển lãm với ba hình thức trưng bày. Kéo để xoay Sảnh Đèn Lồng 3D.',
 hall_eyebrow:'Sảnh Đèn Lồng 3D',hall_desc:'Kéo để xoay hành lang; nhấp vào đèn lồng (bìa) để xem thông tin.',
 new_eyebrow:'Sách mới',new_title:'Sách nhập về tháng này',view_active:'Sinh động',view_list:'Danh mục',
 lib1_t:'Sách đã được thủ thư thẩm định',lib1_d:'Chỉ đăng ký sách được 12 thủ thư thẩm định nội dung, bản dịch và đóng gáy.',lib2_t:'Dữ liệu MARC / thư mục',lib2_d:'Cung cấp KORMARC cùng nhãn và mã vạch cho mọi sách giao.',lib3_t:'Báo giá chính thức tức thì',lib3_d:'In báo giá PDF đã áp dụng chiết khấu cơ quan để đính kèm hồ sơ.',
 search_eyebrow:'Tìm sách · Bổ sung',search_title:'Tìm sách đa văn hóa theo tiêu chí thủ thư',search_ph:'Tên sách, tác giả, ISBN',f_lang:'Ngôn ngữ',f_age:'Độ tuổi',f_stock:'Tình trạng',f_reset:'Đặt lại bộ lọc',sort_new:'Mới nhất',sort_price:'Giá',sort_title:'Tên sách',result_count:'{n} cuốn',
 age_child:'Thiếu nhi',age_teen:'Thiếu niên',age_adult:'Người lớn · Thủ thư',stock_ok:'Có sẵn',stock_wait:'Chờ hàng',
 curpage_title:'Tất cả triển lãm',type_hall:'Sảnh Đèn Lồng 3D',type_stall:'Quầy chợ đêm',type_sky:'Đèn trời',books_n:'{n} cuốn',
 c1_t:'Sách tranh đoạt giải Biennale',c1_d:'Bộ nguyên bản + bản dịch các tác phẩm đoạt giải BIB, Bologna Ragazzi.',c2_t:'Lễ hội và đèn lồng châu Á',c2_d:'Yeondeunghoe, Nguyên tiêu, Songkran, Matsuri — hiểu láng giềng qua lễ hội.',c3_t:'Sách cần đọc cho phụ huynh & thủ thư',c3_d:'Tiếng Hàn đời sống, hướng dẫn phát triển bộ sưu tập, văn học thiếu niên.',
 cart_eyebrow:'Giỏ báo giá',cart_title:'Giỏ báo giá cung ứng',cart_summary:'Tóm tắt',cart_org:'Loại cơ quan',org_public:'Thư viện công cộng (giảm 12%)',org_school:'Thư viện trường (giảm 10%)',org_multi:'Trung tâm gia đình đa văn hóa (giảm 15%)',org_personal:'Cá nhân (0%)',cart_sub:'Tổng giá bìa',cart_disc:'Chiết khấu cơ quan',cart_total:'Tổng dự kiến',cart_note:'Sách miễn VAT. Vận chuyển và xử lý báo giá riêng.',cart_quote:'Phát hành báo giá chính thức',cart_clear:'Xóa giỏ',cart_empty:'Giỏ trống. Hãy tìm và thêm sách.',
 back:'Quay lại',add:'Thêm vào giỏ',added:'Đã thêm vào giỏ',removed:'Đã xóa khỏi giỏ',cleared:'Đã xóa giỏ',quote_done:'Mở cửa sổ in báo giá (PDF)',
 b_isbn:'ISBN',b_lang:'Ngôn ngữ',b_country:'Xuất xứ',b_age:'Đối tượng',b_pub:'NXB',b_year:'Năm',b_kdc:'KDC',b_pages:'Số trang',b_stock:'Cung ứng',price_unit:'KRW',qty:'SL',footer_desc:'Cung ứng sách thư viện đa văn hóa · cùng thủ thư dựng kệ sách thế giới',th_title:'Tên sách',th_lang:'NN',th_age:'Đối tượng',th_pub:'NXB',th_price:'Giá',th_stock:'Cung ứng',th_act:''},
zh:{brand:'灯笼图书馆',brand_sub:'Lantern Night Library · 多元文化图书供应',nav_home:'首页',nav_search:'图书检索',nav_curation:'策展',nav_cart:'报价篮',
 hero_eyebrow:'2026 多元文化图书馆供应平台',hero_title:'灯笼之下<br>世界的<em>故事</em><br>在此汇聚',hero_desc:'来自480家出版社、12种语言的多元文化图书，由馆员审核后供应。报价单、MARC数据与加工一站完成。',hero_cta1:'检索·采购',hero_cta2:'进入灯笼展厅',stat_lang:'支持语言',stat_books:'收录图书',stat_lib:'供应馆',hero_hint:'移动鼠标让灯笼摇曳 · 点击迸出火星',
 notice:'2026下半年公共图书馆多元文化资料采购支持项目 — 9月底报价截止',notice_link:'开具报价单',
 cur_eyebrow:'策展 · Curated Exhibitions',cur_title:'如灯笼般悬挂的本月策展',cur_desc:'三种不同展示形式的策展。3D灯笼展厅可拖动环视。',
 hall_eyebrow:'3D 灯笼展厅',hall_desc:'拖动旋转回廊，点击灯笼（封面）查看书目信息。',
 new_eyebrow:'新书 · New Arrivals',new_title:'本月到馆新书',view_active:'动态',view_list:'书目列表',
 lib1_t:'馆员审核图书',lib1_d:'仅收录经12位在职馆员审核内容、翻译与装订质量的图书。',lib2_t:'提供 MARC/书目数据',lib2_d:'随书提供 KORMARC 数据及标签、条码加工。',lib3_t:'即时开具公文报价单',lib3_d:'已含机构折扣的报价单可直接导出PDF附于公文。',
 search_eyebrow:'图书检索 · 采购',search_title:'以馆员标准检索多元文化图书',search_ph:'书名、作者、ISBN',f_lang:'语言',f_age:'适读年龄',f_stock:'供应状态',f_reset:'重置筛选',sort_new:'最新到馆',sort_price:'价格',sort_title:'书名',result_count:'{n} 册',
 age_child:'幼儿·小学',age_teen:'青少年',age_adult:'成人·馆员',stock_ok:'即时供应',stock_wait:'待到货',
 curpage_title:'全部策展',type_hall:'3D 灯笼展厅',type_stall:'夜市摊位',type_sky:'天灯',books_n:'收录 {n} 册',
 c1_t:'世界绘本双年展获奖作',c1_d:'BIB、博洛尼亚拉加齐奖获奖作原版+译本套装。',c2_t:'亚洲的节日与灯笼',c2_d:'燃灯会、元宵、宋干、祭典 — 以节日认识邻国文化。',c3_t:'多元家庭家长·馆员必读',c3_d:'生活韩语、馆藏发展指南、青少年文学。',
 cart_eyebrow:'报价篮',cart_title:'供应报价篮',cart_summary:'报价摘要',cart_org:'机构类型',org_public:'公共图书馆（9折）',org_school:'学校图书馆（9折）',org_multi:'多元文化家庭支援中心（85折）',org_personal:'个人购买（无折扣）',cart_sub:'定价合计',cart_disc:'机构折扣',cart_total:'预计供应金额',cart_note:'图书免增值税。运费与加工费另议。',cart_quote:'开具公文报价单',cart_clear:'清空报价篮',cart_empty:'报价篮为空，请检索并加入图书。',
 back:'返回列表',add:'加入报价篮',added:'已加入报价篮',removed:'已从报价篮移除',cleared:'已清空报价篮',quote_done:'打开报价单（PDF）打印窗口',
 b_isbn:'ISBN',b_lang:'语言',b_country:'原产国',b_age:'对象',b_pub:'出版社',b_year:'出版年',b_kdc:'KDC',b_pages:'页数',b_stock:'供应',price_unit:'韩元',qty:'数量',footer_desc:'多元文化图书馆供应 · 与馆员共建世界书架',th_title:'书名',th_lang:'语言',th_age:'对象',th_pub:'出版社',th_price:'定价',th_stock:'供应',th_act:''}
};
/* ---- v9 overrides ---- */
const OV={
ko:{brand:'문화 항로 도서관',brand_sub:'Cartographic Journey · 다문화 도서 납품',hero_eyebrow:'다문화 도서관 납품 · 세계 문화 항로',hero_title:'책으로 잇는<br><em>SILK ROAD</em><br>문화 항로',hero_desc:'하노이에서 울란바토르까지, 다문화 가정의 고향을 잇는 항로를 따라 사서가 검수한 도서를 납품합니다. 원산국별 탐색, 견적서, MARC 데이터까지.',hero_cta1:'원산국으로 검색',hero_cta2:'항로 전시 떠나기',hero_hint:'지구본을 드래그해 돌려보세요 · 항로를 따라 빛이 흐릅니다',legend:'항로 · 원산국 → 서울',
 notice:'2026 하반기 다문화자료 구입 지원사업 — 9월 30일 견적 마감 · 원산국 12개국 원서 직수입',notice_link:'견적서 발급',cur_eyebrow:'기획전 · Expeditions',cur_title:'이달의 항로 기획전',cur_desc:'항로 정거장, 캐러밴 커버플로우, 보물지도 핀 — 세 가지 형태로 떠나는 도서 탐험.',route_eyebrow:'3D Route Exhibition',route_desc:'정거장 버튼이나 휠 스크롤로 카메라가 항로를 따라 이동합니다. 책을 클릭하면 서지정보.',station:'정거장 {i} / {n}',
 new_title:'이번 달 입항한 신간',view_active:'캐러밴',view_list:'서지 목록',caravan_hint:'← 드래그 또는 휠로 넘기기 →',lib1_t:'원서 직수입 · 사서 검수',lib1_d:'12개국 현지 출판사와 직거래하고 현직 사서가 내용·제본을 검수합니다.',lib2_t:'KORMARC · 원어 서지',lib2_d:'원어 표제·저자 병기 서지 데이터와 장비 작업을 함께 제공합니다.',lib3_t:'밀랍 인장 견적서',lib3_d:'기관 할인 반영 견적서를 PDF로 즉시 발급, 기안 첨부용 공문 서식 제공.',
 search_title:'원산국 지도에서 고르는 다문화 도서',search_ph:'제목, 원제, 출판사, ISBN',f_country:'원산국',sort_new:'최신 입항순',type_route:'항로 정거장',type_caravan:'캐러밴 커버플로우',type_treasure:'보물지도 핀',curpage_title:'기획전 전체',cart_eyebrow:'견적함 · Manifest',cart_title:'납품 견적함 (선적 목록)',cart_note:'부가세 면세(도서). 해외 원서는 환율 변동 시 ±3% 조정될 수 있습니다.',cart_quote:'인장 찍어 견적서 발급',footer_desc:'다문화 도서관 납품 · 세계를 잇는 문화 항로',th_country:'원산국'},
en:{brand:'Cultural Route Library',brand_sub:'Cartographic Journey · Multicultural book supply',hero_eyebrow:'Multicultural library supply · world cultural routes',hero_title:'Books along the<br><em>SILK ROAD</em><br>of cultures',hero_desc:'From Hanoi to Ulaanbaatar, we deliver librarian-vetted books along the routes that connect multicultural families to home. Browse by origin, quote, MARC data.',hero_cta1:'Search by origin',hero_cta2:'Start route exhibition',hero_hint:'Drag the globe · light flows along the routes',legend:'Routes · origin → Seoul',
 notice:'2026 H2 multicultural collection grant — quotation deadline Sep 30 · originals imported from 12 countries',notice_link:'Issue quotation',cur_eyebrow:'Expeditions',cur_title:'This month\'s route exhibitions',cur_desc:'Route stations, caravan coverflow, treasure-map pins — three ways to explore.',route_eyebrow:'3D Route Exhibition',route_desc:'Use the station buttons or scroll to move the camera along the route. Click a book for its record.',station:'Station {i} / {n}',
 new_title:'Arrived in port this month',view_active:'Caravan',view_list:'Record list',caravan_hint:'← drag or scroll →',lib1_t:'Direct import · librarian-vetted',lib1_d:'Direct trade with publishers in 12 countries; working librarians review content and binding.',lib2_t:'KORMARC · original-script records',lib2_d:'Bibliographic data with original titles and authors, plus processing.',lib3_t:'Wax-sealed quotation',lib3_d:'Instant PDF quotation with institutional discount and official form.',
 search_title:'Pick multicultural books from the origin map',search_ph:'Title, original title, publisher, ISBN',f_country:'Country of origin',sort_new:'Newest arrivals',type_route:'Route stations',type_caravan:'Caravan coverflow',type_treasure:'Treasure-map pins',curpage_title:'All expeditions',cart_eyebrow:'Manifest',cart_title:'Quotation basket (manifest)',cart_note:'Books are VAT-exempt. Imported originals may adjust ±3% with exchange rates.',cart_quote:'Seal and issue quotation',footer_desc:'Multicultural library supply · routes that connect the world',th_country:'Origin'},
vi:{brand:'Thư viện Hải trình Văn hóa',brand_sub:'Cartographic Journey · Cung ứng sách đa văn hóa',hero_eyebrow:'Cung ứng thư viện đa văn hóa · hải trình văn hóa thế giới',hero_title:'Sách nối liền<br><em>SILK ROAD</em><br>văn hóa',hero_desc:'Từ Hà Nội đến Ulaanbaatar, chúng tôi giao sách đã được thủ thư thẩm định theo hải trình nối gia đình đa văn hóa với quê hương. Tìm theo xuất xứ, báo giá, dữ liệu MARC.',hero_cta1:'Tìm theo xuất xứ',hero_cta2:'Bắt đầu triển lãm hải trình',hero_hint:'Kéo quả địa cầu · ánh sáng chảy theo hải trình',legend:'Hải trình · xuất xứ → Seoul',
 notice:'Dự án hỗ trợ tài liệu đa văn hóa nửa cuối 2026 — hạn báo giá 30/9 · nhập trực tiếp từ 12 quốc gia',notice_link:'Phát hành báo giá',cur_eyebrow:'Chuyến thám hiểm',cur_title:'Triển lãm hải trình tháng này',cur_desc:'Trạm hải trình, đoàn lữ hành, ghim bản đồ kho báu — ba cách khám phá.',route_eyebrow:'Triển lãm hải trình 3D',route_desc:'Dùng nút trạm hoặc cuộn chuột để camera di chuyển theo hải trình. Nhấp vào sách để xem thông tin.',station:'Trạm {i} / {n}',
 new_title:'Sách cập cảng tháng này',view_active:'Đoàn lữ hành',view_list:'Danh mục',caravan_hint:'← kéo hoặc cuộn →',lib1_t:'Nhập trực tiếp · thủ thư thẩm định',lib1_d:'Giao dịch trực tiếp với NXB 12 quốc gia; thủ thư thẩm định nội dung và đóng gáy.',lib2_t:'KORMARC · thư mục nguyên ngữ',lib2_d:'Dữ liệu thư mục kèm tên gốc, tác giả gốc và xử lý kỹ thuật.',lib3_t:'Báo giá đóng dấu sáp',lib3_d:'Báo giá PDF tức thì có chiết khấu cơ quan và mẫu công văn.',
 search_title:'Chọn sách đa văn hóa từ bản đồ xuất xứ',search_ph:'Tên sách, tên gốc, NXB, ISBN',f_country:'Quốc gia xuất xứ',sort_new:'Mới cập cảng',type_route:'Trạm hải trình',type_caravan:'Đoàn lữ hành',type_treasure:'Ghim bản đồ kho báu',curpage_title:'Tất cả chuyến thám hiểm',cart_eyebrow:'Bản kê hàng',cart_title:'Giỏ báo giá (bản kê)',cart_note:'Sách miễn VAT. Sách nhập có thể điều chỉnh ±3% theo tỷ giá.',cart_quote:'Đóng dấu và phát hành báo giá',footer_desc:'Cung ứng thư viện đa văn hóa · hải trình nối liền thế giới',th_country:'Xuất xứ'},
zh:{brand:'文化航路图书馆',brand_sub:'Cartographic Journey · 多元文化图书供应',hero_eyebrow:'多元文化图书馆供应 · 世界文化航路',hero_title:'以书相连的<br><em>SILK ROAD</em><br>文化航路',hero_desc:'从河内到乌兰巴托，沿着连接多元家庭与故乡的航路，交付馆员审核的图书。按原产国浏览、报价单、MARC数据。',hero_cta1:'按原产国检索',hero_cta2:'开启航路展',hero_hint:'拖动地球仪 · 光沿航路流动',legend:'航路 · 原产国 → 首尔',
 notice:'2026下半年多元文化资料采购支持项目 — 9月30日报价截止 · 12国原版直进口',notice_link:'开具报价单',cur_eyebrow:'策展 · 远征',cur_title:'本月航路策展',cur_desc:'航路站点、商队封面流、藏宝图图钉 — 三种探索形式。',route_eyebrow:'3D 航路展',route_desc:'使用站点按钮或滚轮让镜头沿航路移动。点击图书查看书目。',station:'站点 {i} / {n}',
 new_title:'本月到港新书',view_active:'商队',view_list:'书目列表',caravan_hint:'← 拖动或滚动 →',lib1_t:'原版直进口 · 馆员审核',lib1_d:'与12国出版社直接交易，在职馆员审核内容与装订。',lib2_t:'KORMARC · 原文书目',lib2_d:'提供原文书名、作者并记的书目数据及加工。',lib3_t:'蜡封报价单',lib3_d:'即时PDF报价单，含机构折扣与公文格式。',
 search_title:'从原产国地图挑选多元文化图书',search_ph:'书名、原名、出版社、ISBN',f_country:'原产国',sort_new:'最新到港',type_route:'航路站点',type_caravan:'商队封面流',type_treasure:'藏宝图图钉',curpage_title:'全部策展',cart_eyebrow:'舱单',cart_title:'供应报价篮（舱单）',cart_note:'图书免增值税。进口原版可能随汇率调整±3%。',cart_quote:'盖印并开具报价单',footer_desc:'多元文化图书馆供应 · 连接世界的文化航路',th_country:'原产国'}
};
Object.keys(OV).forEach(l=>Object.assign(I18N[l],OV[l]));
CURATIONS[0].type='route';CURATIONS[1].type='caravan';CURATIONS[2].type='treasure';
const CITY={'한국':{n:'SEOUL',la:37.5,lo:127},'베트남':{n:'HANOI',la:21,lo:105.8},'미국':{n:'NEW YORK',la:40.7,lo:-74},'중국':{n:'BEIJING',la:39.9,lo:116.4},'몽골':{n:'ULAANBAATAR',la:47.9,lo:106.9},'필리핀':{n:'MANILA',la:14.6,lo:121},'태국':{n:'BANGKOK',la:13.7,lo:100.5},'러시아':{n:'MOSCOW',la:55.7,lo:37.6},'우즈베키스탄':{n:'TASHKENT',la:41.3,lo:69.2},'네팔':{n:'KATHMANDU',la:27.7,lo:85.3},'일본':{n:'TOKYO',la:35.7,lo:139.7},'인도네시아':{n:'JAKARTA',la:-6.2,lo:106.8}};

let lang=localStorage.getItem('v9_lang')||'ko';
const t=(k,vars)=>{let s=(I18N[lang]&&I18N[lang][k])||I18N.ko[k]||k;if(vars)Object.keys(vars).forEach(v=>s=s.replace('{'+v+'}',vars[v]));return s;};
function applyI18n(){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>el.innerHTML=t(el.dataset.i18n));document.querySelectorAll('[data-i18n-ph]').forEach(el=>el.placeholder=t(el.dataset.i18nPh));document.querySelectorAll('#lang-switch button').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));renderAll();}
document.querySelectorAll('#lang-switch button').forEach(b=>b.addEventListener('click',()=>{lang=b.dataset.lang;localStorage.setItem('v9_lang',lang);applyI18n();}));
const $=s=>document.querySelector(s);const fmt=n=>n.toLocaleString('ko-KR')+' '+t('price_unit');const byId=id=>BOOKS.find(b=>b.id===+id);
function coverHTML(b){return `<div class="book-cover" style="background:linear-gradient(150deg,${b.color[0]},${b.color[1]})"><div class="t">${b.title}</div><div class="l">${(CITY[b.country]||{}).n||''}</div></div>`;}
function stockTag(b){return `<span class="tag ${b.stock}">${t('stock_'+b.stock)}</span>`;}
function toast(m){const el=$('#toast');el.textContent=m;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),1800);}

/* FX: wax seal */
document.addEventListener('click',e=>{const b=e.target.closest('.seal-btn,.btn,.chip,.mini-btn,.route-tabs button,.view-toggle button');if(!b)return;b.classList.add('press');setTimeout(()=>b.classList.remove('press'),150);const w=document.createElement('span');w.className='wax';w.textContent='✦';b.appendChild(w);const s=document.createElement('span');s.className='ink-spread';b.appendChild(s);setTimeout(()=>{w.remove();s.remove();},750);});

/* CART */
let cart=JSON.parse(localStorage.getItem('v9_cart')||'{}');
function saveCart(){localStorage.setItem('v9_cart',JSON.stringify(cart));$('#cart-count').textContent=Object.values(cart).reduce((a,b)=>a+b,0);const cb=$('#cart-btn');cb.classList.remove('pulse');void cb.offsetWidth;cb.classList.add('pulse');}
function addToCart(id,q=1){cart[id]=(cart[id]||0)+q;saveCart();toast(t('added'));renderCart();}
function removeFromCart(id){delete cart[id];saveCart();toast(t('removed'));renderCart();}
function setQty(id,q){q=Math.max(1,Math.min(999,+q||1));cart[id]=q;saveCart();renderCart();}
document.addEventListener('click',e=>{const a=e.target.closest('[data-add]');if(a){e.preventDefault();e.stopPropagation();addToCart(a.dataset.add);}});
function renderCart(){const wrap=$('#cart-items');const ids=Object.keys(cart);wrap.innerHTML=ids.length?ids.map(id=>{const b=byId(id);return `<div class="cart-row">${coverHTML(b)}<div><h4>${b.title}</h4><div class="muted"><span class="isbn">${b.isbn}</span> · ${b.country} · ${b.pub}</div>${stockTag(b)}</div><div class="qty"><button data-q="-1" data-id="${id}">−</button><input value="${cart[id]}" data-qin="${id}"><button data-q="1" data-id="${id}">+</button></div><b style="color:var(--seal);font-family:var(--disp)">${fmt(b.price*cart[id])}</b><button class="del" data-del="${id}"><span class="material-symbols-outlined">close</span></button></div>`;}).join(''):`<div class="cart-empty">${t('cart_empty')}</div>`;const rate=+$('#org-type').value;const sub=ids.reduce((s,id)=>s+byId(id).price*cart[id],0);const disc=Math.round(sub*rate);$('#sum-sub').textContent=fmt(sub);$('#sum-disc').textContent='− '+fmt(disc);$('#sum-total').textContent=fmt(sub-disc);}
$('#cart-items').addEventListener('click',e=>{const q=e.target.closest('[data-q]');if(q)setQty(q.dataset.id,cart[q.dataset.id]+ +q.dataset.q);const d=e.target.closest('[data-del]');if(d)removeFromCart(d.dataset.del);});
$('#cart-items').addEventListener('change',e=>{if(e.target.dataset.qin)setQty(e.target.dataset.qin,e.target.value);});
$('#org-type').addEventListener('change',renderCart);$('#btn-clear').addEventListener('click',()=>{cart={};saveCart();renderCart();toast(t('cleared'));});
$('#btn-quote').addEventListener('click',()=>{toast(t('quote_done'));const ids=Object.keys(cart);if(!ids.length)return;const rate=+$('#org-type').value;const sub=ids.reduce((s,id)=>s+byId(id).price*cart[id],0);const w=window.open('','_blank');w.document.write(`<html><head><meta charset="utf-8"><title>견적서</title><style>body{font-family:serif;padding:40px;background:#f3e8cf}table{width:100%;border-collapse:collapse}td,th{border:1px solid #8a3b1f;padding:8px;font-size:13px}h1{letter-spacing:.3em;color:#8a3b1f}</style></head><body><h1>견 적 서</h1><p>문화 항로 도서관 · 다문화 도서 납품 · ${new Date().toLocaleDateString('ko-KR')}</p><table><tr><th>No</th><th>서명</th><th>원산국</th><th>ISBN</th><th>정가</th><th>수량</th><th>금액</th></tr>${ids.map((id,i)=>{const b=byId(id);return `<tr><td>${i+1}</td><td>${b.title}</td><td>${b.country}</td><td>${b.isbn}</td><td>${b.price.toLocaleString()}</td><td>${cart[id]}</td><td>${(b.price*cart[id]).toLocaleString()}</td></tr>`}).join('')}</table><p>정가 합계 ${sub.toLocaleString()}원 · 기관 할인 ${rate*100}% · <b>납품 금액 ${(sub-Math.round(sub*rate)).toLocaleString()}원</b></p><script>window.print()<\/script></body></html>`);w.document.close();});

/* ROUTER */
let detailScene=null,curScene=null;
function route(){const h=(location.hash||'#home').slice(1);const [page,param]=h.split('/');document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));($('#page-'+page)||$('#page-home')).classList.remove('hidden');document.querySelectorAll('.main-nav a').forEach(a=>a.classList.toggle('active',a.dataset.route===page));window.scrollTo({top:0});if(page==='detail')renderDetail(param);if(page==='curation')renderCurationPage(param);if(page==='cart')renderCart();if(page==='search')renderResults();}
addEventListener('hashchange',route);

/* CURATION cards */
function curVisual(c){const books=BOOKS.filter(b=>b.cur.includes(c.id));
 if(c.type==='route')return `<div class="cur-visual"><svg viewBox="0 0 400 300"><path d="M30 230 C 120 200, 140 90, 230 110 S 330 60, 380 30" fill="none" stroke="#8a3b1f" stroke-width="3" stroke-dasharray="8 7"/>${books.slice(0,5).map((b,i)=>{const pts=[[30,230],[130,150],[230,110],[300,90],[380,30]];return `<rect x="${pts[i][0]-14}" y="${pts[i][1]-40}" width="28" height="40" rx="2" fill="${b.color[0]}"/><circle cx="${pts[i][0]}" cy="${pts[i][1]}" r="5" fill="#8a3b1f"/>`;}).join('')}</svg></div>`;
 if(c.type==='caravan')return `<div class="cur-visual"><div class="mini-caravan">${books.slice(0,7).map((b,i)=>`<i style="background:linear-gradient(150deg,${b.color[0]},${b.color[1]});transform:rotateY(${(i-3)*-25}deg) translateZ(${-Math.abs(i-3)*30}px)"></i>`).join('')}</div></div>`;
 return `<div class="cur-visual"><svg viewBox="0 0 400 300"><path d="M40 260 Q 120 120 200 180 T 360 60" fill="none" stroke="#8a3b1f" stroke-width="2" stroke-dasharray="6 6"/><text x="330" y="90" font-family="Cinzel" font-size="34" fill="#8a3b1f">✕</text>${books.slice(0,5).map((b,i)=>`<g><circle cx="${60+i*70}" cy="${200-(i*37)%90}" r="7" fill="#8a3b1f"/><rect x="${48+i*70}" y="${160-(i*37)%90}" width="24" height="34" rx="2" fill="${b.color[0]}"/></g>`).join('')}</svg></div>`;}
function curCard(c){const n=BOOKS.filter(b=>b.cur.includes(c.id)).length;return `<a href="#curation/${c.id}" class="cur-card seal-btn">${curVisual(c)}<span class="type">${t('type_'+c.type)}</span><h3>${t(c.titleKey)}</h3><p>${t(c.descKey)}</p><span class="count">${t('books_n',{n})}</span></a>`;}
function renderHomeCurations(){$('#home-curations').innerHTML=CURATIONS.map(curCard).join('');$('#cur-list').innerHTML=CURATIONS.map(curCard).join('');}

/* CARAVAN coverflow (CSS 3D) */
function makeCaravan(track,books){let idx=Math.floor(books.length/2);track.innerHTML=books.map(b=>`<a href="#detail/${b.id}" class="caravan-item">${coverHTML(b)}<h4>${b.title}</h4><div class="meta">${b.country} · ${b.pub}</div><div class="price">${fmt(b.price)}</div></a>`).join('');const items=[...track.children];
 function layout(){items.forEach((el,i)=>{const d=i-idx;el.style.transform=`translateX(${d*190}px) translateZ(${-Math.abs(d)*160}px) rotateY(${-Math.sign(d)*Math.min(Math.abs(d),2)*30}deg)`;el.style.opacity=Math.abs(d)>4?0:1;el.style.zIndex=100-Math.abs(d);});}
 layout();const wrap=track.parentElement;let sx=0,drag=false,moved=0;wrap.addEventListener('mousedown',e=>{drag=true;sx=e.clientX;moved=0;});addEventListener('mouseup',()=>drag=false);wrap.addEventListener('mousemove',e=>{if(!drag)return;const dx=e.clientX-sx;if(Math.abs(dx)>60){idx=Math.max(0,Math.min(books.length-1,idx-Math.sign(dx)));sx=e.clientX;moved++;layout();}});
 wrap.addEventListener('wheel',e=>{e.preventDefault();idx=Math.max(0,Math.min(books.length-1,idx+Math.sign(e.deltaY+e.deltaX)));layout();},{passive:false});
 items.forEach((el,i)=>el.addEventListener('click',e=>{if(i!==idx){e.preventDefault();idx=i;layout();}}));}

/* NEW books */
function renderNew(){const news=BOOKS.filter(b=>b.new);makeCaravan($('#caravan-track'),news);
 $('#new-list').innerHTML=`<table><thead><tr><th>ISBN</th><th>${t('th_title')}</th><th>${t('th_country')}</th><th>${t('th_lang')}</th><th>${t('th_age')}</th><th>${t('th_pub')}</th><th>${t('th_price')}</th><th>${t('th_stock')}</th><th></th></tr></thead><tbody>${news.map(b=>`<tr><td class="isbn">${b.isbn}</td><td><a href="#detail/${b.id}"><b>${b.title}</b><br><span class="muted">${b.orig}</span></a></td><td>${b.country}</td><td>${LANG_NAMES[b.lang]}</td><td>${t('age_'+b.age)}</td><td>${b.pub}</td><td>${fmt(b.price)}</td><td>${stockTag(b)}</td><td><button class="mini-btn" data-add="${b.id}">${t('add')}</button></td></tr>`).join('')}</tbody></table>`;}
$('#new-toggle').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;document.querySelectorAll('#new-toggle button').forEach(x=>x.classList.toggle('active',x===b));$('#new-active').classList.toggle('hidden',b.dataset.view!=='active');$('#new-list').classList.toggle('hidden',b.dataset.view!=='list');});

/* SEARCH + map picker */
const filters={country:new Set(),age:new Set(),stock:new Set()};
function mapXY(c){return [ (c.lo+180)/360*1000, (90-c.la)/180*500 ];}
function renderMapPicker(){const countries=[...new Set(BOOKS.map(b=>b.country))];$('#map-picker').innerHTML=`<svg viewBox="150 60 700 260" preserveAspectRatio="xMidYMid meet"><defs><pattern id="wave" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M0 20 Q10 10 20 20 T40 20" fill="none" stroke="#a88a5e" stroke-width=".6" opacity=".5"/></pattern></defs><rect x="0" y="0" width="1000" height="500" fill="url(#wave)"/>${countries.filter(c=>c!=='한국').map(c=>{const [x,y]=mapXY(CITY[c]);const [sx,sy]=mapXY(CITY['한국']);return `<path d="M${x} ${y} Q ${(x+sx)/2} ${Math.min(y,sy)-40} ${sx} ${sy}" fill="none" stroke="#8a3b1f" stroke-width="1" stroke-dasharray="4 4" opacity=".5"/>`;}).join('')}${countries.map(c=>{const [x,y]=mapXY(CITY[c]);return `<g class="pin ${filters.country.has(c)?'active':''}" data-c="${c}"><circle cx="${x}" cy="${y}" r="7"/><text x="${x+10}" y="${y+4}">${CITY[c].n}</text></g>`;}).join('')}</svg>`;}
$('#map-picker').addEventListener('click',e=>{const p=e.target.closest('.pin');if(!p)return;const c=p.dataset.c;filters.country.has(c)?filters.country.delete(c):filters.country.add(c);renderFilterChips();renderMapPicker();renderResults();});
function renderFilterChips(){const cs=[...new Set(BOOKS.map(b=>b.country))];$('#f-country').innerHTML=cs.map(c=>`<button class="chip ${filters.country.has(c)?'active':''}" data-f="country" data-v="${c}">${c}</button>`).join('');$('#f-age').innerHTML=['child','teen','adult'].map(a=>`<button class="chip ${filters.age.has(a)?'active':''}" data-f="age" data-v="${a}">${t('age_'+a)}</button>`).join('');$('#f-stock').innerHTML=['ok','wait'].map(s=>`<button class="chip ${filters.stock.has(s)?'active':''}" data-f="stock" data-v="${s}">${t('stock_'+s)}</button>`).join('');}
$('.filters').addEventListener('click',e=>{const c=e.target.closest('.chip');if(!c)return;const set=filters[c.dataset.f];set.has(c.dataset.v)?set.delete(c.dataset.v):set.add(c.dataset.v);renderFilterChips();renderMapPicker();renderResults();});
$('#f-reset').addEventListener('click',()=>{Object.values(filters).forEach(s=>s.clear());$('#q').value='';renderFilterChips();renderMapPicker();renderResults();});
$('#q').addEventListener('input',renderResults);$('#sort').addEventListener('change',renderResults);
function renderResults(){const q=$('#q').value.trim().toLowerCase();let list=BOOKS.filter(b=>(!q||b.title.toLowerCase().includes(q)||b.orig.toLowerCase().includes(q)||b.isbn.includes(q)||b.pub.toLowerCase().includes(q))&&(!filters.country.size||filters.country.has(b.country))&&(!filters.age.size||filters.age.has(b.age))&&(!filters.stock.size||filters.stock.has(b.stock)));const s=$('#sort').value;if(s==='price')list.sort((a,b)=>a.price-b.price);else if(s==='title')list.sort((a,b)=>a.title.localeCompare(b.title));else list.sort((a,b)=>b.year-a.year||b.id-a.id);$('#result-count').textContent=t('result_count',{n:list.length});$('#results').innerHTML=list.map(b=>`<a href="#detail/${b.id}" class="res-card">${coverHTML(b)}<div><h4>${b.title}</h4><div class="meta">${b.orig}<br>${b.country} · ${LANG_NAMES[b.lang]} · ${t('age_'+b.age)}<br><span class="isbn">${b.isbn}</span></div><div class="price">${fmt(b.price)}</div>${stockTag(b)} <button class="mini-btn" data-add="${b.id}">${t('add')}</button></div></a>`).join('');}

/* THREE helpers */
function coverTexture(b){const c=document.createElement('canvas');c.width=256;c.height=360;const g=c.getContext('2d');const gr=g.createLinearGradient(0,0,256,360);gr.addColorStop(0,b.color[0]);gr.addColorStop(1,b.color[1]);g.fillStyle=gr;g.fillRect(0,0,256,360);g.fillStyle='rgba(0,0,0,.25)';g.fillRect(0,0,14,360);g.fillStyle='#fff';g.font='800 26px "Noto Serif KR", serif';g.shadowColor='rgba(0,0,0,.4)';g.shadowBlur=6;const words=b.title.split(' ');let line='',y=50;for(const w of words){const test=line?line+' '+w:w;if(g.measureText(test).width>215){g.fillText(line,26,y);line=w;y+=32;}else line=test;}g.fillText(line,26,y);g.font='14px Cinzel, serif';g.fillStyle='rgba(255,255,255,.9)';g.fillText((CITY[b.country]||{}).n||'',26,330);return new THREE.CanvasTexture(c);}
function fitRenderer(r,cv){const w=cv.clientWidth,h=cv.clientHeight;r.setSize(w,h,false);return w/h;}
function ll2v(la,lo,r){const phi=(90-la)*Math.PI/180,th=(lo+180)*Math.PI/180;return new THREE.Vector3(-r*Math.sin(phi)*Math.cos(th),r*Math.cos(phi),r*Math.sin(phi)*Math.sin(th));}
function bookMesh(b,w=1.4,h=2,d=.18){const paper=new THREE.MeshStandardMaterial({color:0xf3ead6});return new THREE.Mesh(new THREE.BoxGeometry(w,h,d),[new THREE.MeshStandardMaterial({color:new THREE.Color(b.color[0]).multiplyScalar(.8)}),paper,paper,paper,new THREE.MeshStandardMaterial({map:coverTexture(b),roughness:.55}),new THREE.MeshStandardMaterial({color:new THREE.Color(b.color[1]).multiplyScalar(.7)})]);}

/* HERO: cartographic globe */
(function hero(){const cv=$('#hero-canvas');const renderer=new THREE.WebGLRenderer({canvas:cv,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(40,1,.1,100);camera.position.set(0,1,15);
 scene.add(new THREE.AmbientLight(0xffffff,.9));const dl=new THREE.DirectionalLight(0xfff2d0,.6);dl.position.set(5,8,6);scene.add(dl);
 const G=new THREE.Group();G.position.x=3.6;scene.add(G);const R=4.2;
 G.add(new THREE.Mesh(new THREE.SphereGeometry(R-.02,48,48),new THREE.MeshStandardMaterial({color:0xe9dcc0,roughness:1,transparent:true,opacity:.92})));
 G.add(new THREE.Mesh(new THREE.SphereGeometry(R,36,24),new THREE.MeshBasicMaterial({color:0x8a6a3a,wireframe:true,transparent:true,opacity:.35})));
 // land-ish dots
 const pg=new THREE.BufferGeometry();const arr=[];for(let i=0;i<2600;i++){const la=(Math.random()-.5)*160,lo=(Math.random()-.5)*360;const land=(la>5&&la<70&&lo>-10&&lo<150)||(la>-35&&la<35&&lo>-20&&lo<50)||(la>15&&la<70&&lo>-130&&lo<-60)||(la>-55&&la<10&&lo>-80&&lo<-35)||(la>-40&&la<-10&&lo>110&&lo<155);if(!land)continue;const v=ll2v(la,lo,R+.02);arr.push(v.x,v.y,v.z);}pg.setAttribute('position',new THREE.Float32BufferAttribute(arr,3));G.add(new THREE.Points(pg,new THREE.PointsMaterial({color:0x6b4a2e,size:.05})));
 // pins + arcs
 const seoul=ll2v(37.5,127,R);const arcs=[];const pinMeshes=[];const legend=[];
 Object.keys(CITY).forEach(k=>{const c=CITY[k];const p=ll2v(c.la,c.lo,R);const pin=new THREE.Mesh(new THREE.SphereGeometry(.09,10,10),new THREE.MeshBasicMaterial({color:0x8a3b1f}));pin.position.copy(p);G.add(pin);pinMeshes.push(pin);const stick=new THREE.Mesh(new THREE.CylinderGeometry(.015,.015,.5),new THREE.MeshBasicMaterial({color:0x8a3b1f}));stick.position.copy(p.clone().multiplyScalar(1+.25/R));stick.lookAt(0,0,0);stick.rotateX(Math.PI/2);G.add(stick);
  if(k==='한국')return;const mid=p.clone().add(seoul).multiplyScalar(.5);const dist=p.distanceTo(seoul);mid.setLength(R+.4+dist*.35);const curve=new THREE.QuadraticBezierCurve3(p,mid,seoul);const pts=curve.getPoints(60);const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineDashedMaterial({color:0x8a3b1f,dashSize:.15,gapSize:.1,transparent:true,opacity:.8}));line.computeLineDistances();G.add(line);const mover=new THREE.Mesh(new THREE.SphereGeometry(.07,8,8),new THREE.MeshBasicMaterial({color:0xc9a86a}));G.add(mover);arcs.push({curve,mover,ph:Math.random()});legend.push(c.n);});
 $('#hero-legend').innerHTML=`<b style="font-size:.7rem;margin-bottom:.2rem">${t('legend')}</b>`+legend.slice(0,6).map(n=>`<span>${n} → SEOUL</span>`).join('');
 // compass ring
 const ring=new THREE.Mesh(new THREE.TorusGeometry(R+1.1,.02,8,80),new THREE.MeshBasicMaterial({color:0x8a3b1f,transparent:true,opacity:.5}));ring.rotation.x=Math.PI/2;G.add(ring);
 let drag=false,lx=0,vel=0,ry=-1.6,rx=.3;cv.addEventListener('mousedown',e=>{drag=true;lx=e.clientX;cv.style.cursor='grabbing';});addEventListener('mouseup',()=>{drag=false;cv.style.cursor='grab';});cv.addEventListener('mousemove',e=>{if(!drag)return;vel=(e.clientX-lx)*.006;ry+=vel;lx=e.clientX;});
 const clock=new THREE.Clock();(function anim(){requestAnimationFrame(anim);const t0=clock.getElapsedTime();camera.aspect=fitRenderer(renderer,cv);camera.updateProjectionMatrix();if(!drag){vel*=.95;ry+=vel+.0025;}G.rotation.y=ry;G.rotation.x=rx;G.position.y=Math.sin(t0*.6)*.15;arcs.forEach(a=>{const u=(t0*.12+a.ph)%1;a.mover.position.copy(a.curve.getPoint(u));});pinMeshes.forEach((p,i)=>p.scale.setScalar(1+Math.sin(t0*3+i)*.25));renderer.render(scene,camera);})();})();

/* ROUTE exhibition (three.js camera dolly) */
function makeRoute(cv,tip,books,stationEl){const renderer=new THREE.WebGLRenderer({canvas:cv,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;const scene=new THREE.Scene();scene.fog=new THREE.Fog(0xe5d5b3,14,40);const camera=new THREE.PerspectiveCamera(45,1,.1,100);
 scene.add(new THREE.AmbientLight(0xffffff,.8));const dl=new THREE.DirectionalLight(0xfff2d0,.9);dl.position.set(5,12,6);dl.castShadow=true;dl.shadow.mapSize.set(2048,2048);dl.shadow.camera.left=-30;dl.shadow.camera.right=30;dl.shadow.camera.top=30;dl.shadow.camera.bottom=-30;scene.add(dl);
 const ground=new THREE.Mesh(new THREE.PlaneGeometry(120,120),new THREE.MeshStandardMaterial({color:0xe5d5b3,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
 const n=books.length;const pts=books.map((b,i)=>new THREE.Vector3(i*5,0,Math.sin(i*1.1)*3.5));const curve=new THREE.CatmullRomCurve3(pts);const cp=curve.getPoints(n*20);const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(cp.map(p=>p.clone().setY(.03))),new THREE.LineDashedMaterial({color:0x8a3b1f,dashSize:.4,gapSize:.25}));line.computeLineDistances();scene.add(line);
 const meshes=[];books.forEach((b,i)=>{const p=pts[i];const ped=new THREE.Mesh(new THREE.CylinderGeometry(.9,1,.35,24),new THREE.MeshStandardMaterial({color:0xc9b48b}));ped.position.set(p.x,.17,p.z);ped.castShadow=true;ped.receiveShadow=true;scene.add(ped);const m=bookMesh(b,1.5,2.1,.2);m.position.set(p.x,.35+1.05,p.z);m.castShadow=true;m.userData={book:b,i};scene.add(m);meshes.push(m);const pin=new THREE.Mesh(new THREE.ConeGeometry(.12,.4,8),new THREE.MeshBasicMaterial({color:0x8a3b1f}));pin.position.set(p.x,3,p.z);pin.rotation.x=Math.PI;scene.add(pin);});
 let cur=0;const camPos=new THREE.Vector3(),look=new THREE.Vector3();function target(){const p=pts[cur];camPos.set(p.x-2.5,2.6,p.z+6.5);look.set(p.x,1.2,p.z);stationEl.textContent=t('station',{i:cur+1,n})+' · '+books[cur].title;}target();camera.position.copy(camPos);
 const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let hover=null;
 cv.addEventListener('mousemove',e=>{const r=cv.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height*2-1));ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(meshes)[0];hover=hit?hit.object:null;if(hover){tip.style.opacity=1;tip.style.left=(e.clientX-r.left+14)+'px';tip.style.top=(e.clientY-r.top+14)+'px';tip.innerHTML=`<b>${hover.userData.book.title}</b>${hover.userData.book.country} · ${fmt(hover.userData.book.price)}`;cv.style.cursor='pointer';}else{tip.style.opacity=0;cv.style.cursor='default';}});
 cv.addEventListener('click',()=>{if(hover){if(hover.userData.i===cur)location.hash='#detail/'+hover.userData.book.id;else{cur=hover.userData.i;target();}}});
 cv.addEventListener('wheel',e=>{e.preventDefault();cur=Math.max(0,Math.min(n-1,cur+Math.sign(e.deltaY)));target();},{passive:false});
 const api={next(){cur=Math.min(n-1,cur+1);target();},prev(){cur=Math.max(0,cur-1);target();},dispose(){alive=false;renderer.dispose();}};
 let alive=true;const clock=new THREE.Clock();(function anim(){if(!alive)return;requestAnimationFrame(anim);const t0=clock.getElapsedTime();camera.aspect=fitRenderer(renderer,cv);camera.updateProjectionMatrix();camera.position.lerp(camPos,.05);const cl=camera.userData.l||(camera.userData.l=look.clone());cl.lerp(look,.05);camera.lookAt(cl);meshes.forEach((m,i)=>{m.rotation.y=Math.sin(t0*.8+i)*.15+(m===hover?-.3:0);m.position.y=1.4+(i===cur?Math.sin(t0*2)*.08+.15:0);});renderer.render(scene,camera);})();return api;}
let homeRoute=null;
function initHomeRoute(id){if(homeRoute)homeRoute.dispose();const c=CURATIONS.find(x=>x.id===id);$('#route-title').textContent=t(c.titleKey);homeRoute=makeRoute($('#route-canvas'),$('#route-tooltip'),BOOKS.filter(b=>b.cur.includes(id)),$('#route-station'));$('#route-tabs').innerHTML=CURATIONS.map(x=>`<button class="${x.id===id?'active':''}" data-route-tab="${x.id}">${t(x.titleKey)}</button>`).join('');}
$('#route-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-route-tab]');if(b)initHomeRoute(+b.dataset.routeTab);});
$('#route-next').addEventListener('click',()=>homeRoute&&homeRoute.next());$('#route-prev').addEventListener('click',()=>homeRoute&&homeRoute.prev());

/* CURATION page */
function renderCurationPage(id){const wrap=$('#cur-detail');if(curScene){curScene.dispose();curScene=null;}if(!id){wrap.innerHTML='';return;}const c=CURATIONS.find(x=>x.id===+id);if(!c)return;const books=BOOKS.filter(b=>b.cur.includes(c.id));let stage='';
 if(c.type==='route')stage=`<div class="route-wrap"><canvas id="cur-route-canvas"></canvas><div class="route-nav"><button class="seal-btn" id="cur-prev"><span class="material-symbols-outlined">arrow_back</span></button><span id="cur-station"></span><button class="seal-btn" id="cur-next"><span class="material-symbols-outlined">arrow_forward</span></button></div><div class="route-tooltip" id="cur-route-tooltip"></div></div>`;
 else if(c.type==='caravan')stage=`<div class="caravan cur-caravan"><div class="caravan-track" id="cur-caravan"></div><div class="caravan-hint">${t('caravan_hint')}</div></div>`;
 else{const pos=books.map((b,i)=>[8+i*(84/Math.max(books.length-1,1)),30+((i*41)%45)]);stage=`<div class="treasure"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><path d="M${pos.map(p=>p[0]+' '+p[1]).join(' L ')}" fill="none" stroke="#8a3b1f" stroke-width=".4" stroke-dasharray="1.2 1" vector-effect="non-scaling-stroke"/></svg>${books.map((b,i)=>`<a href="#detail/${b.id}" class="tpin" style="left:${pos[i][0]}%;top:${pos[i][1]+18}%">${coverHTML(b)}<small>${(CITY[b.country]||{}).n||''}</small></a>`).join('')}<div style="position:absolute;right:1rem;bottom:.8rem;font-family:Cinzel;color:#8a3b1f;font-size:2rem">✕</div></div>`;}
 wrap.innerHTML=`<span class="eyebrow">${t('type_'+c.type)}</span><h2 style="font-family:var(--serif);font-size:2rem;margin:.2rem 0;font-weight:800">${t(c.titleKey)}</h2><p style="color:var(--ink2)">${t(c.descKey)}</p>${stage}<div class="cur-books">${books.map(b=>`<a href="#detail/${b.id}" class="res-card">${coverHTML(b)}<div><h4>${b.title}</h4><div class="meta">${b.country} · ${b.pub}<br><span class="isbn">${b.isbn}</span></div><div class="price">${fmt(b.price)}</div><button class="mini-btn" data-add="${b.id}">${t('add')}</button></div></a>`).join('')}</div>`;
 if(c.type==='route'){curScene=makeRoute($('#cur-route-canvas'),$('#cur-route-tooltip'),books,$('#cur-station'));$('#cur-next').onclick=()=>curScene.next();$('#cur-prev').onclick=()=>curScene.prev();}
 if(c.type==='caravan')makeCaravan($('#cur-caravan'),books);setTimeout(()=>wrap.scrollIntoView({behavior:'smooth'}),50);}

/* DETAIL */
function renderDetail(id){const b=byId(id)||BOOKS[0];const wrap=$('#detail');if(detailScene){detailScene.dispose();detailScene=null;}
 wrap.innerHTML=`<div><canvas id="detail-canvas"></canvas><p class="muted" style="text-align:center;margin-top:.6rem;font-family:var(--disp)">DRAG TO ROTATE</p></div><div class="detail-info"><span class="eyebrow">${(CITY[b.country]||{}).n||''} · ${b.country} · ${LANG_NAMES[b.lang]}</span><h2>${b.title}</h2><div class="orig">${b.orig}</div><div class="price">${fmt(b.price)}</div>${stockTag(b)}
 <div class="biblio"><div><span>${t('b_isbn')}</span><b class="isbn">${b.isbn}</b></div><div><span>${t('b_pub')}</span><b>${b.pub}</b></div><div><span>${t('b_lang')}</span><b>${LANG_NAMES[b.lang]}</b></div><div><span>${t('b_year')}</span><b>${b.year}</b></div><div><span>${t('b_country')}</span><b>${b.country}</b></div><div><span>${t('b_kdc')}</span><b>${b.kdc}</b></div><div><span>${t('b_age')}</span><b>${t('age_'+b.age)}</b></div><div><span>${t('b_pages')}</span><b>${b.pages}p</b></div></div><p class="desc">${b.desc||''}</p>
 <div class="detail-actions"><div class="qty"><button id="dq-m">−</button><input id="dq" value="1"><button id="dq-p">+</button></div><button class="btn btn-primary seal-btn" id="d-add"><span class="material-symbols-outlined">luggage</span>${t('add')}</button></div></div>`;
 $('#dq-m').onclick=()=>$('#dq').value=Math.max(1,+$('#dq').value-1);$('#dq-p').onclick=()=>$('#dq').value=+$('#dq').value+1;$('#d-add').onclick=()=>addToCart(b.id,+$('#dq').value||1);
 const cv=$('#detail-canvas');const renderer=new THREE.WebGLRenderer({canvas:cv,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(38,1,.1,50);camera.position.set(0,.6,7);scene.add(new THREE.AmbientLight(0xffffff,.8));const dl=new THREE.DirectionalLight(0xfff2d0,.9);dl.position.set(3,6,5);dl.castShadow=true;scene.add(dl);const floor=new THREE.Mesh(new THREE.PlaneGeometry(20,20),new THREE.ShadowMaterial({opacity:.18}));floor.rotation.x=-Math.PI/2;floor.position.y=-1.8;floor.receiveShadow=true;scene.add(floor);
 const book=bookMesh(b,2.2,3.1,.42);book.castShadow=true;scene.add(book);const ring=new THREE.Mesh(new THREE.TorusGeometry(2.6,.02,8,80),new THREE.MeshBasicMaterial({color:0x8a3b1f,transparent:true,opacity:.5}));ring.rotation.x=Math.PI/2;ring.position.y=-1.7;scene.add(ring);
 let drag=false,lx=0,ly=0,ry=0,rx=0,vy=0;cv.onmousedown=e=>{drag=true;lx=e.clientX;ly=e.clientY;};addEventListener('mouseup',()=>drag=false);cv.onmousemove=e=>{if(!drag)return;vy=(e.clientX-lx)*.01;ry+=vy;rx+=(e.clientY-ly)*.006;lx=e.clientX;ly=e.clientY;};
 let alive=true;const clock=new THREE.Clock();(function anim(){if(!alive)return;requestAnimationFrame(anim);const t0=clock.getElapsedTime();camera.aspect=fitRenderer(renderer,cv);camera.updateProjectionMatrix();if(!drag){vy*=.95;ry+=vy+.006;}book.rotation.y=ry;book.rotation.x=rx*.5;book.position.y=Math.sin(t0*1.4)*.08;ring.rotation.z=t0*.2;renderer.render(scene,camera);})();detailScene={dispose(){alive=false;renderer.dispose();}};}

function renderAll(){renderHomeCurations();renderNew();renderFilterChips();renderMapPicker();renderResults();renderCart();initHomeRoute(homeRoute?+($('#route-tabs .active')||{dataset:{routeTab:1}}).dataset.routeTab:1);const h=(location.hash||'#home').slice(1).split('/');if(h[0]==='detail')renderDetail(h[1]);if(h[0]==='curation')renderCurationPage(h[1]);}
applyI18n();saveCart();route();
})();
