/* Atelier Terrazzo v8 — app logic */
(function(){
'use strict';
/* ---------------- DATA ---------------- */
const BOOKS = [
 {id:1, title:'달빛 아래 연등', orig:'Đèn Lồng Dưới Ánh Trăng', lang:'vi', country:'베트남', age:'child', isbn:'9791162341001', price:15000, pub:'Kim Đồng', year:2026, kdc:'833', pages:40, stock:'ok', new:true, color:['#7a2c1f','#c86a3c'], cur:[1,2,3], desc:'베트남 중추절 밤, 아이들이 손수 만든 등불을 들고 마을을 돌며 나누는 이야기. 한국어·베트남어 병기.'},
 {id:2, title:'우리 집 두 개의 설날', orig:'Two New Years at Home', lang:'en', country:'미국', age:'child', isbn:'9791162341002', price:16800, pub:'Candlewick', year:2026, kdc:'843', pages:36, stock:'ok', new:true, color:['#243a5a','#5a86b8'], cur:[1,3], desc:'한국계 미국인 가정이 음력설과 양력설을 함께 보내며 두 문화를 배우는 그림책.'},
 {id:3, title:'할머니의 아오자이', orig:'Chiếc Áo Dài Của Bà', lang:'vi', country:'베트남', age:'child', isbn:'9791162341003', price:14500, pub:'Nhã Nam', year:2025, kdc:'833', pages:44, stock:'ok', new:true, color:['#3c5a2a','#8fb46a'], cur:[1], desc:'베트남 전통 의상 아오자이에 담긴 세 세대 여성의 이야기.'},
 {id:4, title:'별을 세는 밤', orig:'数星星的夜晚', lang:'zh', country:'중국', age:'child', isbn:'9791162341004', price:15500, pub:'接力出版社', year:2026, kdc:'823', pages:32, stock:'wait', new:true, color:['#1f2c4a','#6b7fc4'], cur:[2], desc:'원소절 밤 등불을 띄우며 소원을 비는 소년의 이야기. 한중 이중언어.'},
 {id:5, title:'몽골 초원의 바람 아이', orig:'Салхины хүү', lang:'mn', country:'몽골', age:'teen', isbn:'9791162341005', price:13800, pub:'Монсудар', year:2025, kdc:'893', pages:120, stock:'ok', new:false, color:['#5a3a1f','#c9a86a'], cur:[2,3], desc:'유목민 가정의 소년이 도시 학교로 전학하며 겪는 성장 이야기.'},
 {id:6, title:'필리핀 할아버지의 바다 지도', orig:'Ang Mapa ng Dagat ni Lolo', lang:'tl', country:'필리핀', age:'child', isbn:'9791162341006', price:16000, pub:'Adarna House', year:2026, kdc:'899', pages:40, stock:'ok', new:true, color:['#0f4c5c','#3fa7b5'], cur:[1,2], desc:'섬나라 필리핀의 바다와 가족의 기억을 잇는 지도 이야기.'},
 {id:7, title:'다문화 가정 부모를 위한 첫 한국어 교실', orig:'Korean for Multicultural Parents', lang:'ko', country:'한국', age:'adult', isbn:'9791162341007', price:19000, pub:'한글샘', year:2025, kdc:'710', pages:220, stock:'ok', new:false, color:['#4a2a5a','#a67cc4'], cur:[3], desc:'학교 알림장, 병원, 관공서 등 생활 한국어 회화 중심 교재. 6개 언어 대역.'},
 {id:8, title:'태국의 물축제 송크란', orig:'สงกรานต์ของฉัน', lang:'th', country:'태국', age:'child', isbn:'9791162341008', price:15000, pub:'Nanmeebooks', year:2026, kdc:'899', pages:36, stock:'ok', new:true, color:['#7a1f4a','#d46aa0'], cur:[1,2], desc:'태국 새해 물축제 송크란을 통해 배우는 물과 가족의 의미.'},
 {id:9, title:'러시아 할머니의 마트료시카', orig:'Бабушкина матрёшка', lang:'ru', country:'러시아', age:'child', isbn:'9791162341009', price:16500, pub:'Самокат', year:2025, kdc:'892', pages:40, stock:'ok', new:false, color:['#8a1f1f','#e06060'], cur:[1], desc:'인형 속 인형처럼 이어지는 가족의 이야기.'},
 {id:10, title:'우즈베키스탄의 빵, 논', orig:'Non — O\'zbek noni', lang:'uz', country:'우즈베키스탄', age:'child', isbn:'9791162341010', price:14800, pub:'Yangi asr', year:2026, kdc:'899', pages:32, stock:'wait', new:true, color:['#8a5a1f','#e0a850'], cur:[2]},
 {id:11, title:'사서를 위한 다문화 장서 개발 가이드', orig:'Multicultural Collection Development', lang:'ko', country:'한국', age:'adult', isbn:'9791162341011', price:28000, pub:'도서관문화사', year:2026, kdc:'024', pages:310, stock:'ok', new:true, color:['#2a2a2a','#6a6a6a'], cur:[3], desc:'공공·학교도서관의 다문화 자료 선정 기준, 언어별 출판 시장, 서지 작성 실무.'},
 {id:12, title:'네팔 히말라야의 작은 학교', orig:'हिमालको सानो विद्यालय', lang:'ne', country:'네팔', age:'teen', isbn:'9791162341012', price:13500, pub:'Sajha', year:2025, kdc:'899', pages:96, stock:'ok', new:false, color:['#1f4a3a','#5ab08a'], cur:[2,3]},
 {id:13, title:'일본 여름 축제 마츠리', orig:'なつまつり', lang:'ja', country:'일본', age:'child', isbn:'9791162341013', price:15800, pub:'福音館', year:2026, kdc:'833', pages:32, stock:'ok', new:true, color:['#2f2f5a','#7c7cc4'], cur:[1,2]},
 {id:14, title:'인도네시아 그림자 인형극', orig:'Wayang Kulit', lang:'id', country:'인도네시아', age:'child', isbn:'9791162341014', price:16200, pub:'Gramedia', year:2025, kdc:'899', pages:44, stock:'ok', new:false, color:['#4a1f0f','#c07040'], cur:[1]},
];
const LANG_NAMES={ko:'한국어',en:'영어',vi:'베트남어',zh:'중국어',mn:'몽골어',tl:'필리핀어',th:'태국어',ru:'러시아어',uz:'우즈베크어',ne:'네팔어',ja:'일본어',id:'인도네시아어'};

const CURATIONS = [
 {id:1, type:'hall', titleKey:'c1_t', descKey:'c1_d'},
 {id:2, type:'stall', titleKey:'c2_t', descKey:'c2_d'},
 {id:3, type:'sky', titleKey:'c3_t', descKey:'c3_d'},
];

/* ---------------- I18N ---------------- */
const I18N = {
ko:{brand:'등불 도서관',brand_sub:'Lantern Night Library · 다문화 도서 납품',nav_home:'메인',nav_search:'도서 검색',nav_curation:'큐레이션',nav_cart:'견적함',
 hero_eyebrow:'2026 다문화 도서관 납품 전문 플랫폼',hero_title:'등불 아래<br>세계의 <em>이야기</em>가<br>모입니다',hero_desc:'12개 언어, 480개 출판사의 다문화 도서를 사서의 기준으로 검수해 납품합니다. 견적서 발급부터 서지 데이터(MARC) 제공까지 한 번에.',hero_cta1:'도서 검색·수서',hero_cta2:'등불 전시관 입장',stat_lang:'지원 언어',stat_books:'등록 도서',stat_lib:'납품 도서관',hero_hint:'마우스를 움직여 등불을 흔들어 보세요 · 클릭하면 불티가 날립니다',
 notice:'2026 하반기 공공도서관 다문화자료 구입 지원사업 납품 일정 안내 — 9월 말 견적 마감',notice_link:'견적서 발급하기',
 cur_eyebrow:'기획전 · Curated Exhibitions',cur_title:'등불처럼 걸어둔 이달의 기획전',cur_desc:'전시 형태가 각기 다른 세 개의 기획전. 3D 등불 전시관은 드래그해서 둘러볼 수 있습니다.',
 hall_eyebrow:'3D Lantern Hall',hall_desc:'드래그로 회랑을 돌려보고, 등불(표지)을 클릭하면 서지정보로 이동합니다.',
 new_eyebrow:'신간 · New Arrivals',new_title:'이번 달 입고 신간',view_active:'액티브',view_list:'서지 목록',
 lib1_t:'사서 검수 완료 도서',lib1_d:'현직 사서 12명이 내용·번역·제본 품질을 검수한 도서만 등록합니다.',lib2_t:'MARC/서지 데이터 제공',lib2_d:'납품 도서의 KORMARC 데이터와 장비 작업(라벨·바코드)을 함께 제공합니다.',lib3_t:'공문용 견적서 즉시 발급',lib3_d:'기관 할인율이 반영된 견적서를 PDF로 바로 출력해 기안에 첨부하세요.',
 search_eyebrow:'도서 검색 · 수서',search_title:'사서의 기준으로 찾는 다문화 도서',search_ph:'제목, 저자, ISBN',f_lang:'언어',f_age:'대상 연령',f_stock:'납품 상태',f_reset:'필터 초기화',sort_new:'최신 입고순',sort_price:'가격순',sort_title:'제목순',result_count:'{n}권',
 age_child:'유아·초등',age_teen:'청소년',age_adult:'성인·사서',stock_ok:'즉시 납품',stock_wait:'입고 대기',
 curpage_title:'기획전 전체 보기',type_hall:'3D 등불 전시관',type_stall:'야시장 가판대',type_sky:'하늘 등불',books_n:'{n}권 수록',
 c1_t:'세계 그림책 비엔날레 수상작',c1_d:'BIB·볼로냐 라가치 수상작 중 다문화 가정 아동을 위한 원서+번역서 세트.',c2_t:'아시아의 축제와 등불',c2_d:'연등회, 원소절, 송크란, 마츠리 — 축제로 배우는 이웃 나라 문화.',c3_t:'다문화 가정 부모·사서 필독서',c3_d:'생활 한국어, 장서 개발 가이드, 성장기 청소년 문학까지.',
 cart_eyebrow:'견적함 · Quotation Basket',cart_title:'납품 견적함',cart_summary:'견적 요약',cart_org:'기관 유형',org_public:'공공도서관 (12% 할인)',org_school:'학교도서관 (10% 할인)',org_multi:'다문화가족지원센터 (15% 할인)',org_personal:'개인 구매 (0%)',cart_sub:'정가 합계',cart_disc:'기관 할인',cart_total:'납품 예정 금액',cart_note:'부가세 면세(도서). 배송·장비작업비 별도 협의.',cart_quote:'공문용 견적서 발급',cart_clear:'견적함 비우기',cart_empty:'견적함이 비어 있습니다. 도서를 검색해 담아 주세요.',
 back:'목록으로',add:'견적함 담기',added:'견적함에 담았습니다',removed:'견적함에서 제거했습니다',cleared:'견적함을 비웠습니다',quote_done:'견적서(PDF) 발급 창을 엽니다',
 b_isbn:'ISBN',b_lang:'언어',b_country:'원산국',b_age:'대상',b_pub:'출판사',b_year:'출간',b_kdc:'KDC',b_pages:'쪽수',b_stock:'납품',price_unit:'원',qty:'수량',footer_desc:'다문화 도서관 납품 전문 · 사서와 함께 만드는 세계의 서가',th_title:'서명',th_lang:'언어',th_age:'대상',th_pub:'출판사',th_price:'정가',th_stock:'납품',th_act:''},
en:{brand:'Lantern Library',brand_sub:'Lantern Night Library · Multicultural book supply',nav_home:'Home',nav_search:'Search',nav_curation:'Curation',nav_cart:'Quote Basket',
 hero_eyebrow:'2026 Multicultural library supply platform',hero_title:'Under the lanterns,<br>the world\'s <em>stories</em><br>gather',hero_desc:'Multicultural books in 12 languages from 480 publishers, vetted by librarians. Quotation, MARC data and processing in one place.',hero_cta1:'Search & acquire',hero_cta2:'Enter Lantern Hall',stat_lang:'Languages',stat_books:'Titles',stat_lib:'Libraries served',hero_hint:'Move the mouse to sway the lanterns · click for sparks',
 notice:'2026 H2 public library multicultural collection grant — quotation deadline end of September',notice_link:'Issue a quotation',
 cur_eyebrow:'Curated Exhibitions',cur_title:'This month\'s exhibitions, hung like lanterns',cur_desc:'Three exhibitions in three display forms. Drag the 3D Lantern Hall to look around.',
 hall_eyebrow:'3D Lantern Hall',hall_desc:'Drag to rotate the gallery; click a lantern (cover) to open its record.',
 new_eyebrow:'New Arrivals',new_title:'Arrived this month',view_active:'Active',view_list:'Record list',
 lib1_t:'Librarian-vetted titles',lib1_d:'Only titles reviewed for content, translation and binding by 12 working librarians.',lib2_t:'MARC / bibliographic data',lib2_d:'KORMARC records plus labels and barcodes for every delivered title.',lib3_t:'Official quotation in seconds',lib3_d:'Print a PDF quotation with institutional discount applied, ready for approval.',
 search_eyebrow:'Search · Acquisition',search_title:'Find multicultural books by librarian criteria',search_ph:'Title, author, ISBN',f_lang:'Language',f_age:'Age group',f_stock:'Supply status',f_reset:'Reset filters',sort_new:'Newest',sort_price:'Price',sort_title:'Title',result_count:'{n} titles',
 age_child:'Children',age_teen:'Young adult',age_adult:'Adult · Librarian',stock_ok:'In stock',stock_wait:'Backorder',
 curpage_title:'All exhibitions',type_hall:'3D Lantern Hall',type_stall:'Night market stall',type_sky:'Sky lanterns',books_n:'{n} titles',
 c1_t:'Picture book biennale winners',c1_d:'BIB & Bologna Ragazzi winners as original + translation sets for multicultural children.',c2_t:'Festivals and lanterns of Asia',c2_d:'Yeondeunghoe, Lantern Festival, Songkran, Matsuri — neighbours through festivals.',c3_t:'Must-reads for parents & librarians',c3_d:'Everyday Korean, collection development guides, YA fiction.',
 cart_eyebrow:'Quotation Basket',cart_title:'Supply quotation basket',cart_summary:'Summary',cart_org:'Institution type',org_public:'Public library (12% off)',org_school:'School library (10% off)',org_multi:'Multicultural family center (15% off)',org_personal:'Personal (0%)',cart_sub:'List price total',cart_disc:'Institutional discount',cart_total:'Estimated total',cart_note:'Books are VAT-exempt. Shipping and processing quoted separately.',cart_quote:'Issue official quotation',cart_clear:'Clear basket',cart_empty:'Your basket is empty. Search and add titles.',
 back:'Back to list',add:'Add to basket',added:'Added to basket',removed:'Removed from basket',cleared:'Basket cleared',quote_done:'Opening quotation (PDF) print window',
 b_isbn:'ISBN',b_lang:'Language',b_country:'Origin',b_age:'Audience',b_pub:'Publisher',b_year:'Year',b_kdc:'KDC',b_pages:'Pages',b_stock:'Supply',price_unit:'KRW',qty:'Qty',footer_desc:'Multicultural library supply · building the world\'s shelves with librarians',th_title:'Title',th_lang:'Lang',th_age:'Audience',th_pub:'Publisher',th_price:'Price',th_stock:'Supply',th_act:''},
vi:{brand:'Thư viện Đèn Lồng',brand_sub:'Lantern Night Library · Cung ứng sách đa văn hóa',nav_home:'Trang chủ',nav_search:'Tìm sách',nav_curation:'Triển lãm',nav_cart:'Giỏ báo giá',
 hero_eyebrow:'Nền tảng cung ứng sách cho thư viện đa văn hóa 2026',hero_title:'Dưới ánh đèn lồng,<br><em>câu chuyện</em> của<br>thế giới hội tụ',hero_desc:'Sách đa văn hóa 12 ngôn ngữ từ 480 nhà xuất bản, được thủ thư thẩm định. Báo giá, dữ liệu MARC và xử lý kỹ thuật tại một nơi.',hero_cta1:'Tìm & bổ sung',hero_cta2:'Vào Sảnh Đèn Lồng',stat_lang:'Ngôn ngữ',stat_books:'Đầu sách',stat_lib:'Thư viện phục vụ',hero_hint:'Di chuột để làm đèn lồng đung đưa · nhấp để tóe lửa',
 notice:'Dự án hỗ trợ mua tài liệu đa văn hóa nửa cuối 2026 — hạn báo giá cuối tháng 9',notice_link:'Phát hành báo giá',
 cur_eyebrow:'Triển lãm tuyển chọn',cur_title:'Triển lãm tháng này, treo như đèn lồng',cur_desc:'Ba triển lãm với ba hình thức trưng bày. Kéo để xoay Sảnh Đèn Lồng 3D.',
 hall_eyebrow:'Sảnh Đèn Lồng 3D',hall_desc:'Kéo để xoay hành lang; nhấp vào đèn lồng (bìa) để xem thông tin.',
 new_eyebrow:'Sách mới',new_title:'Sách nhập về tháng này',view_active:'Sinh động',view_list:'Danh mục',
 lib1_t:'Sách đã được thủ thư thẩm định',lib1_d:'Chỉ đăng ký sách được 12 thủ thư thẩm định nội dung, bản dịch và đóng gáy.',lib2_t:'Dữ liệu MARC / thư mục',lib2_d:'Cung cấp KORMARC cùng nhãn và mã vạch cho mọi sách giao.',lib3_t:'Báo giá chính thức tức thì',lib3_d:'In báo giá PDF đã áp dụng chiết khấu cơ quan để đính kèm hồ sơ.',
 search_eyebrow:'Tìm sách · Bổ sung',search_title:'Tìm sách đa văn hóa theo tiêu chí thủ thư',search_ph:'Tên sách, tác giả, ISBN',f_lang:'Ngôn ngữ',f_age:'Độ tuổi',f_stock:'Tình trạng',f_reset:'Đặt lại bộ lọc',sort_new:'Mới nhất',sort_price:'Giá',sort_title:'Tên sách',result_count:'{n} cuốn',
 age_child:'Thiếu nhi',age_teen:'Thiếu niên',age_adult:'Người lớn · Thủ thư',stock_ok:'Có sẵn',stock_wait:'Chờ hàng',
 curpage_title:'Tất cả triển lãm',type_hall:'Sảnh Đèn Lồng 3D',type_stall:'Quầy chợ đêm',type_sky:'Đèn trời',books_n:'{n} cuốn',
 c1_t:'Sách tranh đoạt giải Biennale',c1_d:'Bộ nguyên bản + bản dịch các tác phẩm đoạt giải BIB, Bologna Ragazzi.',c2_t:'Lễ hội và đèn lồng châu Á',c2_d:'Yeondeunghoe, Nguyên tiêu, Songkran, Matsuri — hiểu láng giềng qua lễ hội.',c3_t:'Sách cần đọc cho phụ huynh & thủ thư',c3_d:'Tiếng Hàn đời sống, hướng dẫn phát triển bộ sưu tập, văn học thiếu niên.',
 cart_eyebrow:'Giỏ báo giá',cart_title:'Giỏ báo giá cung ứng',cart_summary:'Tóm tắt',cart_org:'Loại cơ quan',org_public:'Thư viện công cộng (giảm 12%)',org_school:'Thư viện trường (giảm 10%)',org_multi:'Trung tâm gia đình đa văn hóa (giảm 15%)',org_personal:'Cá nhân (0%)',cart_sub:'Tổng giá bìa',cart_disc:'Chiết khấu cơ quan',cart_total:'Tổng dự kiến',cart_note:'Sách miễn VAT. Vận chuyển và xử lý báo giá riêng.',cart_quote:'Phát hành báo giá chính thức',cart_clear:'Xóa giỏ',cart_empty:'Giỏ trống. Hãy tìm và thêm sách.',
 back:'Quay lại',add:'Thêm vào giỏ',added:'Đã thêm vào giỏ',removed:'Đã xóa khỏi giỏ',cleared:'Đã xóa giỏ',quote_done:'Mở cửa sổ in báo giá (PDF)',
 b_isbn:'ISBN',b_lang:'Ngôn ngữ',b_country:'Xuất xứ',b_age:'Đối tượng',b_pub:'NXB',b_year:'Năm',b_kdc:'KDC',b_pages:'Số trang',b_stock:'Cung ứng',price_unit:'KRW',qty:'SL',footer_desc:'Cung ứng sách thư viện đa văn hóa · cùng thủ thư dựng kệ sách thế giới',th_title:'Tên sách',th_lang:'NN',th_age:'Đối tượng',th_pub:'NXB',th_price:'Giá',th_stock:'Cung ứng',th_act:''},
zh:{brand:'灯笼图书馆',brand_sub:'Lantern Night Library · 多元文化图书供应',nav_home:'首页',nav_search:'图书检索',nav_curation:'策展',nav_cart:'报价篮',
 hero_eyebrow:'2026 多元文化图书馆供应平台',hero_title:'灯笼之下<br>世界的<em>故事</em><br>在此汇聚',hero_desc:'来自480家出版社、12种语言的多元文化图书，由馆员审核后供应。报价单、MARC数据与加工一站完成。',hero_cta1:'检索·采购',hero_cta2:'进入灯笼展厅',stat_lang:'支持语言',stat_books:'收录图书',stat_lib:'供应馆',hero_hint:'移动鼠标让灯笼摇曳 · 点击迸出火星',
 notice:'2026下半年公共图书馆多元文化资料采购支持项目 — 9月底报价截止',notice_link:'开具报价单',
 cur_eyebrow:'策展 · Curated Exhibitions',cur_title:'如灯笼般悬挂的本月策展',cur_desc:'三种不同展示形式的策展。3D灯笼展厅可拖动环视。',
 hall_eyebrow:'3D 灯笼展厅',hall_desc:'拖动旋转回廊，点击灯笼（封面）查看书目信息。',
 new_eyebrow:'新书 · New Arrivals',new_title:'本月到馆新书',view_active:'动态',view_list:'书目列表',
 lib1_t:'馆员审核图书',lib1_d:'仅收录经12位在职馆员审核内容、翻译与装订质量的图书。',lib2_t:'提供 MARC/书目数据',lib2_d:'随书提供 KORMARC 数据及标签、条码加工。',lib3_t:'即时开具公文报价单',lib3_d:'已含机构折扣的报价单可直接导出PDF附于公文。',
 search_eyebrow:'图书检索 · 采购',search_title:'以馆员标准检索多元文化图书',search_ph:'书名、作者、ISBN',f_lang:'语言',f_age:'适读年龄',f_stock:'供应状态',f_reset:'重置筛选',sort_new:'最新到馆',sort_price:'价格',sort_title:'书名',result_count:'{n} 册',
 age_child:'幼儿·小学',age_teen:'青少年',age_adult:'成人·馆员',stock_ok:'即时供应',stock_wait:'待到货',
 curpage_title:'全部策展',type_hall:'3D 灯笼展厅',type_stall:'夜市摊位',type_sky:'天灯',books_n:'收录 {n} 册',
 c1_t:'世界绘本双年展获奖作',c1_d:'BIB、博洛尼亚拉加齐奖获奖作原版+译本套装。',c2_t:'亚洲的节日与灯笼',c2_d:'燃灯会、元宵、宋干、祭典 — 以节日认识邻国文化。',c3_t:'多元家庭家长·馆员必读',c3_d:'生活韩语、馆藏发展指南、青少年文学。',
 cart_eyebrow:'报价篮',cart_title:'供应报价篮',cart_summary:'报价摘要',cart_org:'机构类型',org_public:'公共图书馆（9折）',org_school:'学校图书馆（9折）',org_multi:'多元文化家庭支援中心（85折）',org_personal:'个人购买（无折扣）',cart_sub:'定价合计',cart_disc:'机构折扣',cart_total:'预计供应金额',cart_note:'图书免增值税。运费与加工费另议。',cart_quote:'开具公文报价单',cart_clear:'清空报价篮',cart_empty:'报价篮为空，请检索并加入图书。',
 back:'返回列表',add:'加入报价篮',added:'已加入报价篮',removed:'已从报价篮移除',cleared:'已清空报价篮',quote_done:'打开报价单（PDF）打印窗口',
 b_isbn:'ISBN',b_lang:'语言',b_country:'原产国',b_age:'对象',b_pub:'出版社',b_year:'出版年',b_kdc:'KDC',b_pages:'页数',b_stock:'供应',price_unit:'韩元',qty:'数量',footer_desc:'多元文化图书馆供应 · 与馆员共建世界书架',th_title:'书名',th_lang:'语言',th_age:'对象',th_pub:'出版社',th_price:'定价',th_stock:'供应',th_act:''}
};
/* ---- v8 overrides ---- */
const OV={
ko:{brand:'아틀리에 테라조',brand_sub:'Librarian Acquisition Desk',hero_eyebrow:'다문화 도서관 납품 · 사서 우선 설계',hero_title:'사서의 책상 위<br><span>가장 단정한</span><br>수서 도구',hero_desc:'ISBN 일괄 검색, 언어·연령 필터, 기관 할인 견적서까지. 검수된 다문화 도서를 도면처럼 정확하게 납품합니다.',hero_cta1:'ISBN 일괄 검색',hero_cta2:'3D 서가 벽 보기',hero_hint:'마우스로 기울이기 · 클릭하면 블록이 서가로 정렬됩니다',kpi1:'납품 예정',kpi2:'승인 대기 견적',kpi3:'이번 달 입고 신간',kpi_unit:'건',kpi_unit2:'권',
 notice:'2026 하반기 공공도서관 다문화자료 구입 지원사업 — 9월 30일 견적 마감 · MARC 데이터 무상 제공',notice_link:'견적서 발급',cur_eyebrow:'기획전 · Exhibitions',cur_title:'세 가지 전시 형태의 이달 기획전',cur_desc:'3D 서가 벽, 도면 격자, 회전 북스탠드. 사서가 실제 서가를 상상할 수 있도록 설계했습니다.',wall_eyebrow:'3D Shelf Wall',wall_desc:'마우스를 움직이면 서가가 기울고, 책등에 올리면 책이 앞으로 나옵니다. 클릭하면 서지정보.',
 view_active:'3D 틸트',view_list:'데이터 테이블',lib1_t:'사서 검수 도서만',lib2_t:'KORMARC · 장비 작업',lib2_d:'서지 데이터, 라벨, 바코드, RFID 태그까지 납품과 함께 제공.',lib3_t:'공문용 견적서',lib3_d:'기관 할인이 반영된 견적서를 PDF로 즉시 출력해 기안에 첨부.',search_title:'ISBN을 붙여넣으면 바로 견적',search_ph:'제목, 저자, 출판사, ISBN',f_isbn:'ISBN 일괄 입력',isbn_ph:'한 줄에 하나씩 ISBN 붙여넣기',isbn_run:'일괄 조회',isbn_found:'{n}권 일치 · 견적함에 담았습니다',type_wall:'3D 서가 벽',type_blueprint:'도면 격자',type_stand:'회전 북스탠드',curpage_title:'기획전 전체',cart_budget:'예산 (원)',budget_txt:'예산 대비 {p}% 사용',footer_desc:'다문화 도서관 납품 · 사서 우선 수서 데스크',th_shelf:'서가 위치'},
en:{brand:'Atelier Terrazzo',brand_sub:'Librarian Acquisition Desk',hero_eyebrow:'Multicultural library supply · librarian-first',hero_title:'The neatest<br><span>acquisition tool</span><br>on a librarian\'s desk',hero_desc:'Bulk ISBN lookup, language and age filters, institutional quotations. Vetted multicultural titles delivered with blueprint precision.',hero_cta1:'Bulk ISBN search',hero_cta2:'View 3D shelf wall',hero_hint:'Move to tilt · click to snap the blocks into a shelf',kpi1:'Deliveries scheduled',kpi2:'Quotes awaiting approval',kpi3:'New this month',kpi_unit:'',kpi_unit2:'titles',
 notice:'2026 H2 public library multicultural collection grant — quotation deadline Sep 30 · MARC data included',notice_link:'Issue quotation',cur_eyebrow:'Exhibitions',cur_title:'This month\'s exhibitions in three display forms',cur_desc:'3D shelf wall, blueprint grid, rotating book stand — built so librarians can picture the real shelf.',wall_eyebrow:'3D Shelf Wall',wall_desc:'Move the mouse to tilt the shelf; hover a spine to pull the book out; click for the record.',
 view_active:'3D tilt',view_list:'Data table',lib1_t:'Librarian-vetted only',lib2_t:'KORMARC · processing',lib2_d:'Bibliographic data, labels, barcodes and RFID tags delivered with the books.',lib3_t:'Official quotation',lib3_d:'Print a PDF quotation with institutional discount, ready to attach.',search_title:'Paste ISBNs, get a quotation',search_ph:'Title, author, publisher, ISBN',f_isbn:'Bulk ISBN input',isbn_ph:'One ISBN per line',isbn_run:'Look up all',isbn_found:'{n} matched · added to basket',type_wall:'3D shelf wall',type_blueprint:'Blueprint grid',type_stand:'Rotating stand',curpage_title:'All exhibitions',cart_budget:'Budget (KRW)',budget_txt:'{p}% of budget used',footer_desc:'Multicultural library supply · librarian-first acquisition desk',th_shelf:'Shelf'},
vi:{brand:'Atelier Terrazzo',brand_sub:'Bàn bổ sung của thủ thư',hero_eyebrow:'Cung ứng thư viện đa văn hóa · ưu tiên thủ thư',hero_title:'Công cụ bổ sung<br><span>gọn gàng nhất</span><br>trên bàn thủ thư',hero_desc:'Tra cứu ISBN hàng loạt, bộ lọc ngôn ngữ/độ tuổi, báo giá cơ quan. Sách đa văn hóa đã thẩm định, giao chính xác như bản vẽ.',hero_cta1:'Tra ISBN hàng loạt',hero_cta2:'Xem tường kệ 3D',hero_hint:'Di chuột để nghiêng · nhấp để xếp khối thành kệ',kpi1:'Đơn sắp giao',kpi2:'Báo giá chờ duyệt',kpi3:'Sách mới tháng này',kpi_unit:'',kpi_unit2:'cuốn',
 notice:'Dự án hỗ trợ tài liệu đa văn hóa nửa cuối 2026 — hạn báo giá 30/9 · kèm dữ liệu MARC',notice_link:'Phát hành báo giá',cur_eyebrow:'Triển lãm',cur_title:'Triển lãm tháng này với ba hình thức',cur_desc:'Tường kệ 3D, lưới bản vẽ, giá xoay — giúp thủ thư hình dung kệ thật.',wall_eyebrow:'Tường kệ 3D',wall_desc:'Di chuột để nghiêng kệ; rê lên gáy sách để kéo ra; nhấp để xem thông tin.',
 view_active:'Nghiêng 3D',view_list:'Bảng dữ liệu',lib1_t:'Chỉ sách đã thẩm định',lib2_t:'KORMARC · xử lý kỹ thuật',lib2_d:'Dữ liệu thư mục, nhãn, mã vạch, thẻ RFID giao kèm sách.',lib3_t:'Báo giá chính thức',lib3_d:'In báo giá PDF đã áp chiết khấu để đính kèm hồ sơ.',search_title:'Dán ISBN, nhận báo giá ngay',search_ph:'Tên sách, tác giả, NXB, ISBN',f_isbn:'Nhập ISBN hàng loạt',isbn_ph:'Mỗi dòng một ISBN',isbn_run:'Tra cứu tất cả',isbn_found:'{n} khớp · đã thêm vào giỏ',type_wall:'Tường kệ 3D',type_blueprint:'Lưới bản vẽ',type_stand:'Giá xoay',curpage_title:'Tất cả triển lãm',cart_budget:'Ngân sách (KRW)',budget_txt:'Đã dùng {p}% ngân sách',footer_desc:'Cung ứng thư viện đa văn hóa · bàn bổ sung ưu tiên thủ thư',th_shelf:'Vị trí kệ'},
zh:{brand:'水磨石工坊',brand_sub:'馆员采购工作台',hero_eyebrow:'多元文化图书馆供应 · 馆员优先',hero_title:'馆员案头<br><span>最利落的</span><br>采购工具',hero_desc:'ISBN批量检索、语言与年龄筛选、机构折扣报价单。经审核的多元文化图书，如图纸般精准交付。',hero_cta1:'ISBN 批量检索',hero_cta2:'查看3D书架墙',hero_hint:'移动鼠标倾斜 · 点击让书块排成书架',kpi1:'待交付',kpi2:'待审批报价',kpi3:'本月到馆新书',kpi_unit:'件',kpi_unit2:'册',
 notice:'2026下半年公共图书馆多元文化资料采购支持项目 — 9月30日报价截止 · 免费提供MARC数据',notice_link:'开具报价单',cur_eyebrow:'策展',cur_title:'三种展示形式的本月策展',cur_desc:'3D书架墙、图纸网格、旋转书架 — 让馆员能想象真实书架。',wall_eyebrow:'3D 书架墙',wall_desc:'移动鼠标倾斜书架，悬停书脊抽出图书，点击查看书目。',
 view_active:'3D 倾斜',view_list:'数据表格',lib1_t:'仅馆员审核图书',lib2_t:'KORMARC · 加工',lib2_d:'随书提供书目数据、标签、条码与RFID标签。',lib3_t:'公文报价单',lib3_d:'含机构折扣的报价单即时导出PDF。',search_title:'粘贴ISBN即刻报价',search_ph:'书名、作者、出版社、ISBN',f_isbn:'ISBN 批量输入',isbn_ph:'每行一个ISBN',isbn_run:'批量查询',isbn_found:'匹配 {n} 册 · 已加入报价篮',type_wall:'3D 书架墙',type_blueprint:'图纸网格',type_stand:'旋转书架',curpage_title:'全部策展',cart_budget:'预算（韩元）',budget_txt:'已使用预算 {p}%',footer_desc:'多元文化图书馆供应 · 馆员优先采购台',th_shelf:'架位'}
};
Object.keys(OV).forEach(l=>Object.assign(I18N[l],OV[l]));
CURATIONS[0].type='wall'; CURATIONS[1].type='blueprint'; CURATIONS[2].type='stand';
const SHELF=['A-1','A-2','B-1','B-3','C-2','C-4','D-1','D-2','E-1','E-3','F-2','G-1','G-4','H-2'];

let lang = localStorage.getItem('v8_lang') || 'ko';
const t=(k,vars)=>{let s=(I18N[lang]&&I18N[lang][k])||I18N.ko[k]||k; if(vars) Object.keys(vars).forEach(v=>s=s.replace('{'+v+'}',vars[v])); return s;};
function applyI18n(){ document.documentElement.lang=lang; document.querySelectorAll('[data-i18n]').forEach(el=>el.innerHTML=t(el.dataset.i18n)); document.querySelectorAll('[data-i18n-ph]').forEach(el=>el.placeholder=t(el.dataset.i18nPh)); document.querySelectorAll('#lang-switch button').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang)); renderAll(); }
document.querySelectorAll('#lang-switch button').forEach(b=>b.addEventListener('click',()=>{lang=b.dataset.lang;localStorage.setItem('v8_lang',lang);applyI18n();}));

const $=s=>document.querySelector(s); const fmt=n=>n.toLocaleString('ko-KR')+' '+t('price_unit'); const byId=id=>BOOKS.find(b=>b.id===+id);
function coverHTML(b){return `<div class="book-cover" style="background:linear-gradient(150deg,${b.color[0]},${b.color[1]})"><div class="t">${b.title}</div><div class="l">${b.lang.toUpperCase()} · ${b.country}</div></div>`;}
function stockTag(b){return `<span class="tag ${b.stock}">${t('stock_'+b.stock)}</span>`;}
function toast(m){const el=$('#toast');el.textContent=m;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),1800);}

/* FX: stamp press */
document.addEventListener('click',e=>{const b=e.target.closest('.stamp-btn,.btn,.chip,.mini-btn,.wall-tabs button,.view-toggle button'); if(!b) return; b.classList.add('pressed'); setTimeout(()=>b.classList.remove('pressed'),140); const ink=document.createElement('span'); ink.className='stamp-ink'; b.appendChild(ink); setTimeout(()=>ink.remove(),600);});

/* CART */
let cart=JSON.parse(localStorage.getItem('v8_cart')||'{}');
function saveCart(){localStorage.setItem('v8_cart',JSON.stringify(cart));$('#cart-count').textContent=Object.values(cart).reduce((a,b)=>a+b,0);const cb=$('#cart-btn');cb.classList.remove('pulse');void cb.offsetWidth;cb.classList.add('pulse');}
function addToCart(id,q=1,silent){cart[id]=(cart[id]||0)+q;saveCart();if(!silent)toast(t('added'));renderCart();}
function removeFromCart(id){delete cart[id];saveCart();toast(t('removed'));renderCart();}
function setQty(id,q){q=Math.max(1,Math.min(999,+q||1));cart[id]=q;saveCart();renderCart();}
document.addEventListener('click',e=>{const a=e.target.closest('[data-add]');if(a){e.preventDefault();e.stopPropagation();addToCart(a.dataset.add);}});
function renderCart(){const wrap=$('#cart-items');const ids=Object.keys(cart);
 wrap.innerHTML=ids.length?ids.map(id=>{const b=byId(id);return `<div class="cart-row">${coverHTML(b)}<div><h4>${b.title}</h4><div class="muted"><span class="isbn">${b.isbn}</span> · ${LANG_NAMES[b.lang]} · ${b.pub}</div>${stockTag(b)}</div><div class="qty"><button data-q="-1" data-id="${id}">−</button><input value="${cart[id]}" data-qin="${id}"><button data-q="1" data-id="${id}">+</button></div><b style="color:var(--navy);font-family:var(--mono)">${fmt(b.price*cart[id])}</b><button class="del" data-del="${id}"><span class="material-symbols-outlined">close</span></button></div>`;}).join(''):`<div class="cart-empty">${t('cart_empty')}</div>`;
 const rate=+$('#org-type').value;const sub=ids.reduce((s,id)=>s+byId(id).price*cart[id],0);const disc=Math.round(sub*rate);const total=sub-disc;
 $('#sum-sub').textContent=fmt(sub);$('#sum-disc').textContent='− '+fmt(disc);$('#sum-total').textContent=fmt(total);
 const bud=+$('#budget').value||1;const p=Math.round(total/bud*100);const f=$('#budget-fill');f.style.width=Math.min(p,100)+'%';f.classList.toggle('over',p>100);$('#budget-text').textContent=t('budget_txt',{p});}
$('#cart-items').addEventListener('click',e=>{const q=e.target.closest('[data-q]');if(q)setQty(q.dataset.id,cart[q.dataset.id]+ +q.dataset.q);const d=e.target.closest('[data-del]');if(d)removeFromCart(d.dataset.del);});
$('#cart-items').addEventListener('change',e=>{if(e.target.dataset.qin)setQty(e.target.dataset.qin,e.target.value);});
$('#org-type').addEventListener('change',renderCart);$('#budget').addEventListener('input',renderCart);
$('#btn-clear').addEventListener('click',()=>{cart={};saveCart();renderCart();toast(t('cleared'));});
$('#btn-quote').addEventListener('click',()=>{toast(t('quote_done'));const ids=Object.keys(cart);if(!ids.length)return;const rate=+$('#org-type').value;const sub=ids.reduce((s,id)=>s+byId(id).price*cart[id],0);const w=window.open('','_blank');w.document.write(`<html><head><meta charset="utf-8"><title>견적서</title><style>body{font-family:sans-serif;padding:40px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #999;padding:8px;font-size:13px}h1{letter-spacing:.3em}</style></head><body><h1>견 적 서</h1><p>아틀리에 테라조 · 다문화 도서 납품 · ${new Date().toLocaleDateString('ko-KR')}</p><table><tr><th>No</th><th>서명</th><th>ISBN</th><th>출판사</th><th>정가</th><th>수량</th><th>금액</th></tr>${ids.map((id,i)=>{const b=byId(id);return `<tr><td>${i+1}</td><td>${b.title}</td><td>${b.isbn}</td><td>${b.pub}</td><td>${b.price.toLocaleString()}</td><td>${cart[id]}</td><td>${(b.price*cart[id]).toLocaleString()}</td></tr>`}).join('')}</table><p>정가 합계 ${sub.toLocaleString()}원 · 기관 할인 ${rate*100}% · <b>납품 금액 ${(sub-Math.round(sub*rate)).toLocaleString()}원</b></p><script>window.print()<\/script></body></html>`);w.document.close();});

/* ROUTER */
let detailScene=null,curScene=null;
function route(){const h=(location.hash||'#home').slice(1);const [page,param]=h.split('/');document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));($('#page-'+page)||$('#page-home')).classList.remove('hidden');document.querySelectorAll('.main-nav a').forEach(a=>a.classList.toggle('active',a.dataset.route===page));window.scrollTo({top:0});if(page==='detail')renderDetail(param);if(page==='curation')renderCurationPage(param);if(page==='cart')renderCart();if(page==='search')renderResults();}
addEventListener('hashchange',route);

/* CURATION cards */
function curVisual(c){const books=BOOKS.filter(b=>b.cur.includes(c.id));
 if(c.type==='wall')return `<div class="cur-visual"><div class="mini-shelf">${books.map((b,i)=>`<i style="height:${70+(i*23)%40}px;background:${b.color[0]}"></i>`).join('')}</div></div>`;
 if(c.type==='blueprint')return `<div class="cur-visual blueprint">${books.slice(0,6).map((b,i)=>`<i style="left:${14+i*14}%;top:${30+(i%2)*28}px"></i>`).join('')}</div>`;
 return `<div class="cur-visual"><div class="stand"><div>${books.slice(0,6).map((b,i)=>`<i style="background:linear-gradient(${b.color[0]},${b.color[1]});transform:rotateY(${i*60}deg) translateZ(70px)"></i>`).join('')}</div></div></div>`;}
function curCard(c){const n=BOOKS.filter(b=>b.cur.includes(c.id)).length;return `<a href="#curation/${c.id}" class="cur-card stamp-btn">${curVisual(c)}<span class="type">${t('type_'+c.type)}</span><h3>${t(c.titleKey)}</h3><p>${t(c.descKey)}</p><span class="count">${t('books_n',{n})}</span></a>`;}
function renderHomeCurations(){$('#home-curations').innerHTML=CURATIONS.map(curCard).join('');$('#cur-list').innerHTML=CURATIONS.map(curCard).join('');}

/* NEW books */
function renderNew(){const news=BOOKS.filter(b=>b.new);$('#kpi-new').innerHTML=news.length+' <em>'+t('kpi_unit2')+'</em>';
 $('#new-active').innerHTML=news.map(b=>`<a href="#detail/${b.id}" class="tilt-card"><div class="shine"></div>${coverHTML(b)}<h4>${b.title}</h4><div class="meta">${LANG_NAMES[b.lang]} · ${b.pub} · <span class="isbn">${b.isbn}</span></div><div class="price">${fmt(b.price)}</div></a>`).join('');
 $('#new-list').innerHTML=`<table><thead><tr><th>ISBN</th><th>${t('th_title')}</th><th>${t('th_lang')}</th><th>${t('th_age')}</th><th>${t('th_pub')}</th><th>KDC</th><th>${t('th_shelf')}</th><th>${t('th_price')}</th><th>${t('th_stock')}</th><th></th></tr></thead><tbody>${news.map(b=>`<tr><td class="isbn">${b.isbn}</td><td><a href="#detail/${b.id}"><b>${b.title}</b><br><span class="muted">${b.orig}</span></a></td><td>${LANG_NAMES[b.lang]}</td><td>${t('age_'+b.age)}</td><td>${b.pub}</td><td>${b.kdc}</td><td>${SHELF[b.id-1]}</td><td>${fmt(b.price)}</td><td>${stockTag(b)}</td><td><button class="mini-btn" data-add="${b.id}">${t('add')}</button></td></tr>`).join('')}</tbody></table>`;}
$('#new-toggle').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;document.querySelectorAll('#new-toggle button').forEach(x=>x.classList.toggle('active',x===b));$('#new-active').classList.toggle('hidden',b.dataset.view!=='active');$('#new-list').classList.toggle('hidden',b.dataset.view!=='list');});
document.addEventListener('mousemove',e=>{const c=e.target.closest('.tilt-card');if(!c)return;const r=c.getBoundingClientRect();const x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;c.style.transform=`rotateY(${(x-.5)*22}deg) rotateX(${(.5-y)*22}deg)`;c.style.setProperty('--sx',x*100+'%');c.style.setProperty('--sy',y*100+'%');});
document.addEventListener('mouseout',e=>{const c=e.target.closest&&e.target.closest('.tilt-card');if(c&&!c.contains(e.relatedTarget))c.style.transform='';});

/* SEARCH */
const filters={lang:new Set(),age:new Set(),stock:new Set()};let resView='grid';
function renderFilterChips(){const langs=[...new Set(BOOKS.map(b=>b.lang))];$('#f-lang').innerHTML=langs.map(l=>`<button class="chip ${filters.lang.has(l)?'active':''}" data-f="lang" data-v="${l}">${LANG_NAMES[l]}</button>`).join('');$('#f-age').innerHTML=['child','teen','adult'].map(a=>`<button class="chip ${filters.age.has(a)?'active':''}" data-f="age" data-v="${a}">${t('age_'+a)}</button>`).join('');$('#f-stock').innerHTML=['ok','wait'].map(s=>`<button class="chip ${filters.stock.has(s)?'active':''}" data-f="stock" data-v="${s}">${t('stock_'+s)}</button>`).join('');}
$('.filters').addEventListener('click',e=>{const c=e.target.closest('.chip');if(!c)return;const set=filters[c.dataset.f];set.has(c.dataset.v)?set.delete(c.dataset.v):set.add(c.dataset.v);renderFilterChips();renderResults();});
$('#f-reset').addEventListener('click',()=>{Object.values(filters).forEach(s=>s.clear());$('#q').value='';$('#isbn-bulk').value='';renderFilterChips();renderResults();});
$('#q').addEventListener('input',renderResults);$('#sort').addEventListener('change',renderResults);
$('#res-toggle').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;resView=b.dataset.view;document.querySelectorAll('#res-toggle button').forEach(x=>x.classList.toggle('active',x===b));renderResults();});
$('#isbn-run').addEventListener('click',()=>{const isbns=$('#isbn-bulk').value.split(/[\s,]+/).map(s=>s.replace(/-/g,'')).filter(Boolean);let n=0;isbns.forEach(i=>{const b=BOOKS.find(x=>x.isbn===i);if(b){addToCart(b.id,1,true);n++;}});toast(t('isbn_found',{n}));if(n)setTimeout(()=>location.hash='#cart',700);});
function renderResults(){const q=$('#q').value.trim().toLowerCase();let list=BOOKS.filter(b=>(!q||b.title.toLowerCase().includes(q)||b.orig.toLowerCase().includes(q)||b.isbn.includes(q)||b.pub.toLowerCase().includes(q))&&(!filters.lang.size||filters.lang.has(b.lang))&&(!filters.age.size||filters.age.has(b.age))&&(!filters.stock.size||filters.stock.has(b.stock)));const s=$('#sort').value;if(s==='price')list.sort((a,b)=>a.price-b.price);else if(s==='title')list.sort((a,b)=>a.title.localeCompare(b.title));else list.sort((a,b)=>b.year-a.year||b.id-a.id);$('#result-count').textContent=t('result_count',{n:list.length});
 const R=$('#results');if(resView==='list'){R.className='';R.innerHTML=`<table class="results-table"><thead><tr><th>ISBN</th><th>${t('th_title')}</th><th>${t('th_lang')}</th><th>${t('th_age')}</th><th>${t('th_pub')}</th><th>${t('th_price')}</th><th>${t('th_stock')}</th><th></th></tr></thead><tbody>${list.map(b=>`<tr><td class="isbn">${b.isbn}</td><td><a href="#detail/${b.id}"><b>${b.title}</b><br><span class="muted">${b.orig}</span></a></td><td>${LANG_NAMES[b.lang]}</td><td>${t('age_'+b.age)}</td><td>${b.pub}</td><td>${fmt(b.price)}</td><td>${stockTag(b)}</td><td><button class="mini-btn" data-add="${b.id}">${t('add')}</button></td></tr>`).join('')}</tbody></table>`;}
 else{R.className='results-grid';R.innerHTML=list.map(b=>`<a href="#detail/${b.id}" class="res-card">${coverHTML(b)}<div><h4>${b.title}</h4><div class="meta">${b.orig}<br>${LANG_NAMES[b.lang]} · ${t('age_'+b.age)} · ${b.pub}<br><span class="isbn">${b.isbn}</span></div><div class="price">${fmt(b.price)}</div>${stockTag(b)} <button class="mini-btn" data-add="${b.id}">${t('add')}</button></div></a>`).join('');}}

/* THREE helpers */
function coverTexture(b){const c=document.createElement('canvas');c.width=256;c.height=360;const g=c.getContext('2d');const gr=g.createLinearGradient(0,0,256,360);gr.addColorStop(0,b.color[0]);gr.addColorStop(1,b.color[1]);g.fillStyle=gr;g.fillRect(0,0,256,360);g.fillStyle='rgba(0,0,0,.25)';g.fillRect(0,0,14,360);g.fillStyle='#fff';g.font='900 26px "Noto Sans KR", sans-serif';g.shadowColor='rgba(0,0,0,.4)';g.shadowBlur=6;const words=b.title.split(' ');let line='',y=50;for(const w of words){const test=line?line+' '+w:w;if(g.measureText(test).width>215){g.fillText(line,26,y);line=w;y+=32;}else line=test;}g.fillText(line,26,y);g.font='14px "Space Grotesk", sans-serif';g.fillStyle='rgba(255,255,255,.9)';g.fillText(b.lang.toUpperCase()+' · '+b.country,26,330);return new THREE.CanvasTexture(c);}
function spineTexture(b){const c=document.createElement('canvas');c.width=64;c.height=360;const g=c.getContext('2d');g.fillStyle=b.color[0];g.fillRect(0,0,64,360);g.fillStyle=b.color[1];g.fillRect(0,0,64,24);g.fillRect(0,336,64,24);g.save();g.translate(40,180);g.rotate(Math.PI/2);g.fillStyle='#fff';g.font='700 20px "Noto Sans KR", sans-serif';g.textAlign='center';g.fillText(b.title.slice(0,12),0,0);g.restore();return new THREE.CanvasTexture(c);}
function fitRenderer(r,cv){const w=cv.clientWidth,h=cv.clientHeight;r.setSize(w,h,false);return w/h;}
const PAL=[0xe26d5a,0x2b4c7e,0xf2b134,0x4a8f6b,0x141a2a,0x8b5cf6];

/* HERO: terrazzo blocks morphing */
(function hero(){const cv=$('#hero-canvas');const renderer=new THREE.WebGLRenderer({canvas:cv,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;
 const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.set(0,2,14);
 scene.add(new THREE.AmbientLight(0xffffff,.7));const dl=new THREE.DirectionalLight(0xffffff,.9);dl.position.set(5,10,6);dl.castShadow=true;dl.shadow.mapSize.set(1024,1024);scene.add(dl);
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(40,40),new THREE.ShadowMaterial({opacity:.12}));floor.rotation.x=-Math.PI/2;floor.position.y=-3.2;floor.receiveShadow=true;scene.add(floor);
 const group=new THREE.Group();scene.add(group);const blocks=[];const N=42;
 for(let i=0;i<N;i++){const w=.35+Math.random()*.35,h=1.6+Math.random()*1.2,d=1.1;const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color:PAL[i%PAL.length],roughness:.55}));m.castShadow=true;m.receiveShadow=true;
  const scatter=new THREE.Vector3((Math.random()-.5)*12,(Math.random()-.5)*7,(Math.random()-.5)*6);const rot=new THREE.Euler(Math.random()*3,Math.random()*3,Math.random()*3);
  m.position.copy(scatter);m.rotation.copy(rot);m.userData={scatter,rot,w,h,ph:Math.random()*6};group.add(m);blocks.push(m);}
 // shelf targets
 let x=-6,row=0;const perRow=14;blocks.forEach((m,i)=>{if(i%perRow===0){x=-6;row=Math.floor(i/perRow);}m.userData.shelf=new THREE.Vector3(x+m.userData.w/2,row*2.8-3+m.userData.h/2,0);x+=m.userData.w+.08;});
 const shelves=[];for(let r=0;r<3;r++){const s=new THREE.Mesh(new THREE.BoxGeometry(13,.12,1.4),new THREE.MeshStandardMaterial({color:0xd9d2c3}));s.position.set(0,r*2.8-3.06,0);s.receiveShadow=true;s.castShadow=true;s.material.transparent=true;s.material.opacity=0;scene.add(s);shelves.push(s);}
 let mode=0,mx=0,my=0;const par=cv.parentElement;
 par.addEventListener('mousemove',e=>{const r=cv.getBoundingClientRect();mx=(e.clientX-r.left)/r.width*2-1;my=-((e.clientY-r.top)/r.height*2-1);});
 function morph(){mode=1-mode;blocks.forEach((m,i)=>{const u=m.userData;const tgt=mode?u.shelf:u.scatter;gsap.to(m.position,{x:tgt.x,y:tgt.y,z:tgt.z,duration:1.1,delay:i*.012,ease:'power3.inOut'});gsap.to(m.rotation,{x:mode?0:u.rot.x,y:mode?0:u.rot.y,z:mode?0:u.rot.z,duration:1.1,delay:i*.012,ease:'power3.inOut'});});shelves.forEach(s=>gsap.to(s.material,{opacity:mode?1:0,duration:.8,delay:mode?.6:0}));}
 cv.addEventListener('click',morph);setTimeout(morph,1600);setInterval(morph,9000);
 const clock=new THREE.Clock();(function anim(){requestAnimationFrame(anim);const t0=clock.getElapsedTime();camera.aspect=fitRenderer(renderer,cv);camera.updateProjectionMatrix();group.rotation.y+=((mx*.35)-group.rotation.y)*.05;group.rotation.x+=((-my*.2)-group.rotation.x)*.05;shelves.forEach(s=>{s.rotation.y=group.rotation.y;s.rotation.x=group.rotation.x;});if(!mode)blocks.forEach(m=>{m.position.y+=Math.sin(t0+m.userData.ph)*.002;});renderer.render(scene,camera);})();})();

/* SHELF WALL (three.js) */
function makeWall(cv,tip,books){const renderer=new THREE.WebGLRenderer({canvas:cv,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;
 const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(35,1,.1,100);camera.position.set(0,0,13);
 scene.add(new THREE.AmbientLight(0xffffff,.75));const dl=new THREE.DirectionalLight(0xffffff,.8);dl.position.set(4,8,8);dl.castShadow=true;scene.add(dl);
 const wall=new THREE.Group();scene.add(wall);const meshes=[];const rows=2;const perRow=Math.ceil(books.length/rows);
 const back=new THREE.Mesh(new THREE.BoxGeometry(12.5,7.4,.2),new THREE.MeshStandardMaterial({color:0xf1ece1}));back.position.z=-.7;back.receiveShadow=true;wall.add(back);
 for(let r=0;r<=rows;r++){const s=new THREE.Mesh(new THREE.BoxGeometry(12.5,.16,1.6),new THREE.MeshStandardMaterial({color:0xd9d2c3}));s.position.set(0,-3.4+r*3.3,0);s.castShadow=true;s.receiveShadow=true;wall.add(s);}
 books.forEach((b,i)=>{const r=Math.floor(i/perRow),c=i%perRow;const w=.55+((b.id*7)%4)*.1,h=2.2+((b.id*3)%3)*.25;const spine=new THREE.MeshStandardMaterial({map:spineTexture(b),roughness:.6});const cover=new THREE.MeshStandardMaterial({map:coverTexture(b),roughness:.55});const paper=new THREE.MeshStandardMaterial({color:0xf3ead6});
  const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,1.5),[paper,paper,paper,paper,spine,cover]);m.castShadow=true;m.receiveShadow=true;const x=(c-(perRow-1)/2)*1.45;m.position.set(x,-3.4+r*3.3+.08+h/2,0);m.userData={book:b,home:m.position.clone()};wall.add(m);meshes.push(m);});
 const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let hover=null,mx=0,my=0;
 cv.addEventListener('mousemove',e=>{const r=cv.getBoundingClientRect();mx=(e.clientX-r.left)/r.width*2-1;my=-((e.clientY-r.top)/r.height*2-1);mouse.set(mx,my);ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(meshes)[0];hover=hit?hit.object:null;if(hover){tip.style.opacity=1;tip.style.left=(e.clientX-r.left+14)+'px';tip.style.top=(e.clientY-r.top+14)+'px';tip.innerHTML=`<b>${hover.userData.book.title}</b>${hover.userData.book.isbn} · ${fmt(hover.userData.book.price)}`;cv.style.cursor='pointer';}else{tip.style.opacity=0;cv.style.cursor='default';}});
 cv.addEventListener('mouseleave',()=>{hover=null;tip.style.opacity=0;});
 cv.addEventListener('click',()=>{if(hover)location.hash='#detail/'+hover.userData.book.id;});
 let alive=true;(function anim(){if(!alive)return;requestAnimationFrame(anim);camera.aspect=fitRenderer(renderer,cv);camera.updateProjectionMatrix();wall.rotation.y+=((mx*.45)-wall.rotation.y)*.06;wall.rotation.x+=((-my*.18)-wall.rotation.x)*.06;meshes.forEach(m=>{const tz=m===hover?1.1:0;m.position.z+=(tz-m.position.z)*.18;const ry=m===hover?-.35:0;m.rotation.y+=(ry-m.rotation.y)*.15;});renderer.render(scene,camera);})();
 return{dispose(){alive=false;renderer.dispose();}};}
let homeWall=null;
function initHomeWall(id){if(homeWall)homeWall.dispose();const c=CURATIONS.find(x=>x.id===id);$('#wall-title').textContent=t(c.titleKey);homeWall=makeWall($('#wall-canvas'),$('#wall-tooltip'),BOOKS.filter(b=>b.cur.includes(id)));$('#wall-tabs').innerHTML=CURATIONS.map(x=>`<button class="${x.id===id?'active':''}" data-wall="${x.id}">${t(x.titleKey)}</button>`).join('');}
$('#wall-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-wall]');if(b)initHomeWall(+b.dataset.wall);});

/* CURATION page */
function renderCurationPage(id){const wrap=$('#cur-detail');if(curScene){curScene.dispose();curScene=null;}if(!id){wrap.innerHTML='';return;}const c=CURATIONS.find(x=>x.id===+id);if(!c)return;const books=BOOKS.filter(b=>b.cur.includes(c.id));let stage='';
 if(c.type==='wall')stage=`<div class="wall-wrap"><canvas id="cur-wall-canvas"></canvas><div class="wall-tooltip" id="cur-wall-tooltip"></div></div>`;
 else if(c.type==='blueprint')stage=`<div class="blueprint3d">${books.map(b=>`<a href="#detail/${b.id}" class="bp">${coverHTML(b)}<small>${b.isbn}<br>KDC ${b.kdc} · ${SHELF[b.id-1]}</small></a>`).join('')}</div>`;
 else stage=`<div class="stand3d"><div class="ring">${books.map((b,i)=>`<a href="#detail/${b.id}" style="transform:rotateY(${i*360/books.length}deg) translateZ(${books.length*28}px)">${coverHTML(b)}</a>`).join('')}</div></div>`;
 wrap.innerHTML=`<span class="eyebrow">${t('type_'+c.type)}</span><h2 style="font-size:2rem;margin:.2rem 0;font-weight:900">${t(c.titleKey)}</h2><p style="color:var(--ink2)">${t(c.descKey)}</p>${stage}<div class="cur-books">${books.map(b=>`<a href="#detail/${b.id}" class="res-card">${coverHTML(b)}<div><h4>${b.title}</h4><div class="meta">${LANG_NAMES[b.lang]} · ${b.pub}<br><span class="isbn">${b.isbn}</span></div><div class="price">${fmt(b.price)}</div><button class="mini-btn" data-add="${b.id}">${t('add')}</button></div></a>`).join('')}</div>`;
 if(c.type==='wall')curScene=makeWall($('#cur-wall-canvas'),$('#cur-wall-tooltip'),books);setTimeout(()=>wrap.scrollIntoView({behavior:'smooth'}),50);}

/* DETAIL */
function renderDetail(id){const b=byId(id)||BOOKS[0];const wrap=$('#detail');if(detailScene){detailScene.dispose();detailScene=null;}
 wrap.innerHTML=`<div><canvas id="detail-canvas"></canvas><p class="muted" style="text-align:center;margin-top:.6rem;font-family:var(--mono)">DRAG TO ROTATE · 3D PREVIEW</p></div><div class="detail-info"><span class="eyebrow">${LANG_NAMES[b.lang]} · ${b.country} · ${t('age_'+b.age)}</span><h2>${b.title}</h2><div class="orig">${b.orig}</div><div class="price">${fmt(b.price)}</div>${stockTag(b)} <span class="tag">${t('th_shelf')} ${SHELF[b.id-1]}</span>
 <div class="biblio"><div><span>${t('b_isbn')}</span><b class="isbn">${b.isbn}</b></div><div><span>${t('b_pub')}</span><b>${b.pub}</b></div><div><span>${t('b_lang')}</span><b>${LANG_NAMES[b.lang]}</b></div><div><span>${t('b_year')}</span><b>${b.year}</b></div><div><span>${t('b_country')}</span><b>${b.country}</b></div><div><span>${t('b_kdc')}</span><b>${b.kdc}</b></div><div><span>${t('b_age')}</span><b>${t('age_'+b.age)}</b></div><div><span>${t('b_pages')}</span><b>${b.pages}p</b></div></div><p class="desc">${b.desc||''}</p>
 <div class="detail-actions"><div class="qty"><button id="dq-m">−</button><input id="dq" value="1"><button id="dq-p">+</button></div><button class="btn btn-primary stamp-btn" id="d-add"><span class="material-symbols-outlined">inventory_2</span>${t('add')}</button></div></div>`;
 $('#dq-m').onclick=()=>$('#dq').value=Math.max(1,+$('#dq').value-1);$('#dq-p').onclick=()=>$('#dq').value=+$('#dq').value+1;$('#d-add').onclick=()=>addToCart(b.id,+$('#dq').value||1);
 const cv=$('#detail-canvas');const renderer=new THREE.WebGLRenderer({canvas:cv,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(38,1,.1,50);camera.position.set(0,.6,7);
 scene.add(new THREE.AmbientLight(0xffffff,.75));const dl=new THREE.DirectionalLight(0xffffff,.9);dl.position.set(3,6,5);dl.castShadow=true;scene.add(dl);const floor=new THREE.Mesh(new THREE.PlaneGeometry(20,20),new THREE.ShadowMaterial({opacity:.15}));floor.rotation.x=-Math.PI/2;floor.position.y=-1.8;floor.receiveShadow=true;scene.add(floor);
 const paper=new THREE.MeshStandardMaterial({color:0xf3ead6});const book=new THREE.Mesh(new THREE.BoxGeometry(2.2,3.1,.42),[new THREE.MeshStandardMaterial({map:spineTexture(b)}),paper,paper,paper,new THREE.MeshStandardMaterial({map:coverTexture(b),roughness:.5}),new THREE.MeshStandardMaterial({color:new THREE.Color(b.color[1]).multiplyScalar(.7)})]);book.castShadow=true;scene.add(book);
 let drag=false,lx=0,ly=0,ry=0,rx=0,vy=0;cv.onmousedown=e=>{drag=true;lx=e.clientX;ly=e.clientY;};addEventListener('mouseup',()=>drag=false);cv.onmousemove=e=>{if(!drag)return;vy=(e.clientX-lx)*.01;ry+=vy;rx+=(e.clientY-ly)*.006;lx=e.clientX;ly=e.clientY;};
 let alive=true;const clock=new THREE.Clock();(function anim(){if(!alive)return;requestAnimationFrame(anim);const t0=clock.getElapsedTime();camera.aspect=fitRenderer(renderer,cv);camera.updateProjectionMatrix();if(!drag){vy*=.95;ry+=vy+.006;}book.rotation.y=ry;book.rotation.x=rx*.5;book.position.y=Math.sin(t0*1.4)*.08;renderer.render(scene,camera);})();detailScene={dispose(){alive=false;renderer.dispose();}};}

function renderAll(){renderHomeCurations();renderNew();renderFilterChips();renderResults();renderCart();initHomeWall(homeWall?+($('#wall-tabs .active')||{dataset:{wall:1}}).dataset.wall:1);const h=(location.hash||'#home').slice(1).split('/');if(h[0]==='detail')renderDetail(h[1]);if(h[0]==='curation')renderCurationPage(h[1]);}
applyI18n();saveCart();route();
})();
