/* Pop-up Book City v10 — app logic */
(function(){
'use strict';
/* ---------------- DATA ---------------- */
const BOOKS = [
 {id:1, title:'달빛 아래 연등', orig:'Đèn Lồng Dưới Ánh Trăng', lang:'vi', country:'베트남', age:'child', isbn:'9791162341001', price:15000, pub:'Kim Đồng', year:2026, kdc:'833', pages:40, stock:'ok', new:true, color:['#7a2c1f','#c86a3c'], cur:[1,2,3], desc:'베트남 중추절 밤, 아이들이 손수 만든 등불을 들고 마을을 돌며 나누는 이야기. 한국어·베트남어 병기.'},
 {id:2, title:'우리 집 두 개의 설날', orig:'Two New Years at Home', lang:'en', country:'미국', age:'child', isbn:'9791162341002', price:16800, pub:'Candlewick', year:2026, kdc:'843', pages:36, stock:'ok', new:true, color:['#243a5a','#5a86b8'], cur:[1,3], desc:'한국계 미국인 가정이 음력설과 양력설을 함께 보내며 두 문화를 배우는 그림책.'},
 {id:3, title:'할머니의 아오자이', orig:'Chiếc Áo Dài Của Bà', lang:'vi', country:'베트남', age:'child', isbn:'9791162341003', price:14500, pub:'Nhã Nam', year:2025, kdc:'833', pages:44, stock:'ok', new:true, color:['#3c5a2a','#8fb46a'], cur:[1], desc:'베트남 전통 의상 아오자이에 담긴 세 세대 여성의 이야기.'},
 {id:4, title:'별을 세는 밤', orig:'数星星的夜晚', lang:'zh', country:'중국', age:'child', isbn:'9791162341004', price:15500, pub:'接力出版社', year:2026, kdc:'823', pages:32, stock:'wait', new:true, color:['#1f2c4a','#6b7fc4'], cur:[2], desc:'원소절 밤 등불을 띄우며 소원을 비는 소년의 이야기. 한중 이중언어.'},
 {id:5, title:'몽골 초원의 바람 아이', orig:'Салхины хүү', lang:'mn', country:'몽골', age:'teen', isbn:'9791162341005', price:13800, pub:'Монсудар', year:2025, kdc:'893', pages:120, stock:'ok', new:false, color:['#5a3a1f','#c9a86a'], cur:[2,3], desc:'유목민 가정의 소년이 도시 학교로 전학하며 겪는 성장 이야기.'},
 {id:6, title:'필리핀 할아버지의 바다 지도', orig:'Ang Mapa ng Dagat ni Lolo', lang:'tl', country:'필리핀', age:'child', isbn:'9791162341006', price:16000, pub:'Adarna House', year:2026, kdc:'899', pages:40, stock:'ok', new:true, color:['#0f4c5c','#3fa7b5'], cur:[1,2], desc:'섬나라 필리핀의 바다와 가족의 기억을 잇는 지도 이야기.'},
 {id:7, title:'다문화 가정 부모를 위한 첫 한국어 교실', orig:'Korean for Multicultural Parents', lang:'ko', country:'한국', age:'adult', isbn:'9791162341007', price:19000, pub:'한글샘', year:2025, kdc:'710', pages:220, stock:'ok', new:false, color:['#4a2a5a','#a67cc4'], cur:[3], desc:'학교 알림장, 병원, 관공서 등 생활 한국어 회화 중심 교재. 6개 언어 대역.'},
 {id:8, title:'태국의 물축제 송크란', orig:'สงกรานต์ของฉัน', lang:'th', country:'태국', age:'child', isbn:'9791162341008', price:15000, pub:'Nanmeebooks', year:2026, kdc:'899', pages:36, stock:'ok', new:true, color:['#7a1f4a','#d46aa0'], cur:[1,2], desc:'태국 새해 물축제 송크란을 통해 배우는 물과 가족의 의미.'},
 {id:9, title:'러시아 할머니의 마트료시카', orig:'Бабушкина матрёшка', lang:'ru', country:'러시아', age:'child', isbn:'9791162341009', price:16500, pub:'Самокат', year:2025, kdc:'892', pages:40, stock:'ok', new:false, color:['#8a1f1f','#e06060'], cur:[1], desc:'인형 속 인형처럼 이어지는 가족의 이야기.'},
 {id:10, title:'우즈베키스탄의 빵, 논', orig:'Non — O\'zbek noni', lang:'uz', country:'우즈베키스탄', age:'child', isbn:'9791162341010', price:14800, pub:'Yangi asr', year:2026, kdc:'899', pages:32, stock:'wait', new:true, color:['#8a5a1f','#e0a850'], cur:[2]},
 {id:11, title:'사서를 위한 다문화 장서 개발 가이드', orig:'Multicultural Collection Development', lang:'ko', country:'한국', age:'adult', isbn:'9791162341011', price:28000, pub:'도서관문화사', year:2026, kdc:'024', pages:310, stock:'ok', new:true, color:['#2a2a2a','#6a6a6a'], cur:[3], desc:'공공·학교도서관의 다문화 자료 선정 기준, 언어별 출판 시장, 서지 작성 실무.'},
 {id:12, title:'네팔 히말라야의 작은 학교', orig:'हिमालको सानो विद्यालय', lang:'ne', country:'네팔', age:'teen', isbn:'9791162341012', price:13500, pub:'Sajha', year:2025, kdc:'899', pages:96, stock:'ok', new:false, color:['#1f4a3a','#5ab08a'], cur:[2,3]},
 {id:13, title:'일본 여름 축제 마츠리', orig:'なつまつり', lang:'ja', country:'일본', age:'child', isbn:'9791162341013', price:15800, pub:'福音館', year:2026, kdc:'833', pages:32, stock:'ok', new:true, color:['#2f2f5a','#7c7cc4'], cur:[1,2]},
 {id:14, title:'인도네시아 그림자 인형극', orig:'Wayang Kulit', lang:'id', country:'인도네시아', age:'child', isbn:'9791162341014', price:16200, pub:'Gramedia', year:2025, kdc:'899', pages:44, stock:'ok', new:false, color:['#4a1f0f','#c07040'], cur:[1]},
];
const LANG_NAMES={ko:'한국어',en:'영어',vi:'베트남어',zh:'중국어',mn:'몽골어',tl:'필리핀어',th:'태국어',ru:'러시아어',uz:'우즈베크어',ne:'네팔어',ja:'일본어',id:'인도네시아어'};

const CURATIONS = [
 {id:1, type:'hall', titleKey:'c1_t', descKey:'c1_d'},
 {id:2, type:'stall', titleKey:'c2_t', descKey:'c2_d'},
 {id:3, type:'sky', titleKey:'c3_t', descKey:'c3_d'},
];

/* ---------------- I18N ---------------- */
const I18N = {
ko:{brand:'등불 도서관',brand_sub:'Lantern Night Library · 다문화 도서 납품',nav_home:'메인',nav_search:'도서 검색',nav_curation:'큐레이션',nav_cart:'견적함',
 hero_eyebrow:'2026 다문화 도서관 납품 전문 플랫폼',hero_title:'등불 아래<br>세계의 <em>이야기</em>가<br>모입니다',hero_desc:'12개 언어, 480개 출판사의 다문화 도서를 사서의 기준으로 검수해 납품합니다. 견적서 발급부터 서지 데이터(MARC) 제공까지 한 번에.',hero_cta1:'도서 검색·수서',hero_cta2:'등불 전시관 입장',stat_lang:'지원 언어',stat_books:'등록 도서',stat_lib:'납품 도서관',hero_hint:'마우스를 움직여 등불을 흔들어 보세요 · 클릭하면 불티가 날립니다',
 notice:'2026 하반기 공공도서관 다문화자료 구입 지원사업 납품 일정 안내 — 9월 말 견적 마감',notice_link:'견적서 발급하기',
 cur_eyebrow:'기획전 · Curated Exhibitions',cur_title:'등불처럼 걸어둔 이달의 기획전',cur_desc:'전시 형태가 각기 다른 세 개의 기획전. 3D 등불 전시관은 드래그해서 둘러볼 수 있습니다.',
 hall_eyebrow:'3D Lantern Hall',hall_desc:'드래그로 회랑을 돌려보고, 등불(표지)을 클릭하면 서지정보로 이동합니다.',
 new_eyebrow:'신간 · New Arrivals',new_title:'이번 달 입고 신간',view_active:'액티브',view_list:'서지 목록',
 lib1_t:'사서 검수 완료 도서',lib1_d:'현직 사서 12명이 내용·번역·제본 품질을 검수한 도서만 등록합니다.',lib2_t:'MARC/서지 데이터 제공',lib2_d:'납품 도서의 KORMARC 데이터와 장비 작업(라벨·바코드)을 함께 제공합니다.',lib3_t:'공문용 견적서 즉시 발급',lib3_d:'기관 할인율이 반영된 견적서를 PDF로 바로 출력해 기안에 첨부하세요.',
 search_eyebrow:'도서 검색 · 수서',search_title:'사서의 기준으로 찾는 다문화 도서',search_ph:'제목, 저자, ISBN',f_lang:'언어',f_age:'대상 연령',f_stock:'납품 상태',f_reset:'필터 초기화',sort_new:'최신 입고순',sort_price:'가격순',sort_title:'제목순',result_count:'{n}권',
 age_child:'유아·초등',age_teen:'청소년',age_adult:'성인·사서',stock_ok:'즉시 납품',stock_wait:'입고 대기',
 curpage_title:'기획전 전체 보기',type_hall:'3D 등불 전시관',type_stall:'야시장 가판대',type_sky:'하늘 등불',books_n:'{n}권 수록',
 c1_t:'세계 그림책 비엔날레 수상작',c1_d:'BIB·볼로냐 라가치 수상작 중 다문화 가정 아동을 위한 원서+번역서 세트.',c2_t:'아시아의 축제와 등불',c2_d:'연등회, 원소절, 송크란, 마츠리 — 축제로 배우는 이웃 나라 문화.',c3_t:'다문화 가정 부모·사서 필독서',c3_d:'생활 한국어, 장서 개발 가이드, 성장기 청소년 문학까지.',
 cart_eyebrow:'견적함 · Quotation Basket',cart_title:'납품 견적함',cart_summary:'견적 요약',cart_org:'기관 유형',org_public:'공공도서관 (12% 할인)',org_school:'학교도서관 (10% 할인)',org_multi:'다문화가족지원센터 (15% 할인)',org_personal:'개인 구매 (0%)',cart_sub:'정가 합계',cart_disc:'기관 할인',cart_total:'납품 예정 금액',cart_note:'부가세 면세(도서). 배송·장비작업비 별도 협의.',cart_quote:'공문용 견적서 발급',cart_clear:'견적함 비우기',cart_empty:'견적함이 비어 있습니다. 도서를 검색해 담아 주세요.',
 back:'목록으로',add:'견적함 담기',added:'견적함에 담았습니다',removed:'견적함에서 제거했습니다',cleared:'견적함을 비웠습니다',quote_done:'견적서(PDF) 발급 창을 엽니다',
 b_isbn:'ISBN',b_lang:'언어',b_country:'원산국',b_age:'대상',b_pub:'출판사',b_year:'출간',b_kdc:'KDC',b_pages:'쪽수',b_stock:'납품',price_unit:'원',qty:'수량',footer_desc:'다문화 도서관 납품 전문 · 사서와 함께 만드는 세계의 서가',th_title:'서명',th_lang:'언어',th_age:'대상',th_pub:'출판사',th_price:'정가',th_stock:'납품',th_act:''},
en:{brand:'Lantern Library',brand_sub:'Lantern Night Library · Multicultural book supply',nav_home:'Home',nav_search:'Search',nav_curation:'Curation',nav_cart:'Quote Basket',
 hero_eyebrow:'2026 Multicultural library supply platform',hero_title:'Under the lanterns,<br>the world\'s <em>stories</em><br>gather',hero_desc:'Multicultural books in 12 languages from 480 publishers, vetted by librarians. Quotation, MARC data and processing in one place.',hero_cta1:'Search & acquire',hero_cta2:'Enter Lantern Hall',stat_lang:'Languages',stat_books:'Titles',stat_lib:'Libraries served',hero_hint:'Move the mouse to sway the lanterns · click for sparks',
 notice:'2026 H2 public library multicultural collection grant — quotation deadline end of September',notice_link:'Issue a quotation',
 cur_eyebrow:'Curated Exhibitions',cur_title:'This month\'s exhibitions, hung like lanterns',cur_desc:'Three exhibitions in three display forms. Drag the 3D Lantern Hall to look around.',
 hall_eyebrow:'3D Lantern Hall',hall_desc:'Drag to rotate the gallery; click a lantern (cover) to open its record.',
 new_eyebrow:'New Arrivals',new_title:'Arrived this month',view_active:'Active',view_list:'Record list',
 lib1_t:'Librarian-vetted titles',lib1_d:'Only titles reviewed for content, translation and binding by 12 working librarians.',lib2_t:'MARC / bibliographic data',lib2_d:'KORMARC records plus labels and barcodes for every delivered title.',lib3_t:'Official quotation in seconds',lib3_d:'Print a PDF quotation with institutional discount applied, ready for approval.',
 search_eyebrow:'Search · Acquisition',search_title:'Find multicultural books by librarian criteria',search_ph:'Title, author, ISBN',f_lang:'Language',f_age:'Age group',f_stock:'Supply status',f_reset:'Reset filters',sort_new:'Newest',sort_price:'Price',sort_title:'Title',result_count:'{n} titles',
 age_child:'Children',age_teen:'Young adult',age_adult:'Adult · Librarian',stock_ok:'In stock',stock_wait:'Backorder',
 curpage_title:'All exhibitions',type_hall:'3D Lantern Hall',type_stall:'Night market stall',type_sky:'Sky lanterns',books_n:'{n} titles',
 c1_t:'Picture book biennale winners',c1_d:'BIB & Bologna Ragazzi winners as original + translation sets for multicultural children.',c2_t:'Festivals and lanterns of Asia',c2_d:'Yeondeunghoe, Lantern Festival, Songkran, Matsuri — neighbours through festivals.',c3_t:'Must-reads for parents & librarians',c3_d:'Everyday Korean, collection development guides, YA fiction.',
 cart_eyebrow:'Quotation Basket',cart_title:'Supply quotation basket',cart_summary:'Summary',cart_org:'Institution type',org_public:'Public library (12% off)',org_school:'School library (10% off)',org_multi:'Multicultural family center (15% off)',org_personal:'Personal (0%)',cart_sub:'List price total',cart_disc:'Institutional discount',cart_total:'Estimated total',cart_note:'Books are VAT-exempt. Shipping and processing quoted separately.',cart_quote:'Issue official quotation',cart_clear:'Clear basket',cart_empty:'Your basket is empty. Search and add titles.',
 back:'Back to list',add:'Add to basket',added:'Added to basket',removed:'Removed from basket',cleared:'Basket cleared',quote_done:'Opening quotation (PDF) print window',
 b_isbn:'ISBN',b_lang:'Language',b_country:'Origin',b_age:'Audience',b_pub:'Publisher',b_year:'Year',b_kdc:'KDC',b_pages:'Pages',b_stock:'Supply',price_unit:'KRW',qty:'Qty',footer_desc:'Multicultural library supply · building the world\'s shelves with librarians',th_title:'Title',th_lang:'Lang',th_age:'Audience',th_pub:'Publisher',th_price:'Price',th_stock:'Supply',th_act:''},
vi:{brand:'Thư viện Đèn Lồng',brand_sub:'Lantern Night Library · Cung ứng sách đa văn hóa',nav_home:'Trang chủ',nav_search:'Tìm sách',nav_curation:'Triển lãm',nav_cart:'Giỏ báo giá',
 hero_eyebrow:'Nền tảng cung ứng sách cho thư viện đa văn hóa 2026',hero_title:'Dưới ánh đèn lồng,<br><em>câu chuyện</em> của<br>thế giới hội tụ',hero_desc:'Sách đa văn hóa 12 ngôn ngữ từ 480 nhà xuất bản, được thủ thư thẩm định. Báo giá, dữ liệu MARC và xử lý kỹ thuật tại một nơi.',hero_cta1:'Tìm & bổ sung',hero_cta2:'Vào Sảnh Đèn Lồng',stat_lang:'Ngôn ngữ',stat_books:'Đầu sách',stat_lib:'Thư viện phục vụ',hero_hint:'Di chuột để làm đèn lồng đung đưa · nhấp để tóe lửa',
 notice:'Dự án hỗ trợ mua tài liệu đa văn hóa nửa cuối 2026 — hạn báo giá cuối tháng 9',notice_link:'Phát hành báo giá',
 cur_eyebrow:'Triển lãm tuyển chọn',cur_title:'Triển lãm tháng này, treo như đèn lồng',cur_desc:'Ba triển lãm với ba hình thức trưng bày. Kéo để xoay Sảnh Đèn Lồng 3D.',
 hall_eyebrow:'Sảnh Đèn Lồng 3D',hall_desc:'Kéo để xoay hành lang; nhấp vào đèn lồng (bìa) để xem thông tin.',
 new_eyebrow:'Sách mới',new_title:'Sách nhập về tháng này',view_active:'Sinh động',view_list:'Danh mục',
 lib1_t:'Sách đã được thủ thư thẩm định',lib1_d:'Chỉ đăng ký sách được 12 thủ thư thẩm định nội dung, bản dịch và đóng gáy.',lib2_t:'Dữ liệu MARC / thư mục',lib2_d:'Cung cấp KORMARC cùng nhãn và mã vạch cho mọi sách giao.',lib3_t:'Báo giá chính thức tức thì',lib3_d:'In báo giá PDF đã áp dụng chiết khấu cơ quan để đính kèm hồ sơ.',
 search_eyebrow:'Tìm sách · Bổ sung',search_title:'Tìm sách đa văn hóa theo tiêu chí thủ thư',search_ph:'Tên sách, tác giả, ISBN',f_lang:'Ngôn ngữ',f_age:'Độ tuổi',f_stock:'Tình trạng',f_reset:'Đặt lại bộ lọc',sort_new:'Mới nhất',sort_price:'Giá',sort_title:'Tên sách',result_count:'{n} cuốn',
 age_child:'Thiếu nhi',age_teen:'Thiếu niên',age_adult:'Người lớn · Thủ thư',stock_ok:'Có sẵn',stock_wait:'Chờ hàng',
 curpage_title:'Tất cả triển lãm',type_hall:'Sảnh Đèn Lồng 3D',type_stall:'Quầy chợ đêm',type_sky:'Đèn trời',books_n:'{n} cuốn',
 c1_t:'Sách tranh đoạt giải Biennale',c1_d:'Bộ nguyên bản + bản dịch các tác phẩm đoạt giải BIB, Bologna Ragazzi.',c2_t:'Lễ hội và đèn lồng châu Á',c2_d:'Yeondeunghoe, Nguyên tiêu, Songkran, Matsuri — hiểu láng giềng qua lễ hội.',c3_t:'Sách cần đọc cho phụ huynh & thủ thư',c3_d:'Tiếng Hàn đời sống, hướng dẫn phát triển bộ sưu tập, văn học thiếu niên.',
 cart_eyebrow:'Giỏ báo giá',cart_title:'Giỏ báo giá cung ứng',cart_summary:'Tóm tắt',cart_org:'Loại cơ quan',org_public:'Thư viện công cộng (giảm 12%)',org_school:'Thư viện trường (giảm 10%)',org_multi:'Trung tâm gia đình đa văn hóa (giảm 15%)',org_personal:'Cá nhân (0%)',cart_sub:'Tổng giá bìa',cart_disc:'Chiết khấu cơ quan',cart_total:'Tổng dự kiến',cart_note:'Sách miễn VAT. Vận chuyển và xử lý báo giá riêng.',cart_quote:'Phát hành báo giá chính thức',cart_clear:'Xóa giỏ',cart_empty:'Giỏ trống. Hãy tìm và thêm sách.',
 back:'Quay lại',add:'Thêm vào giỏ',added:'Đã thêm vào giỏ',removed:'Đã xóa khỏi giỏ',cleared:'Đã xóa giỏ',quote_done:'Mở cửa sổ in báo giá (PDF)',
 b_isbn:'ISBN',b_lang:'Ngôn ngữ',b_country:'Xuất xứ',b_age:'Đối tượng',b_pub:'NXB',b_year:'Năm',b_kdc:'KDC',b_pages:'Số trang',b_stock:'Cung ứng',price_unit:'KRW',qty:'SL',footer_desc:'Cung ứng sách thư viện đa văn hóa · cùng thủ thư dựng kệ sách thế giới',th_title:'Tên sách',th_lang:'NN',th_age:'Đối tượng',th_pub:'NXB',th_price:'Giá',th_stock:'Cung ứng',th_act:''},
zh:{brand:'灯笼图书馆',brand_sub:'Lantern Night Library · 多元文化图书供应',nav_home:'首页',nav_search:'图书检索',nav_curation:'策展',nav_cart:'报价篮',
 hero_eyebrow:'2026 多元文化图书馆供应平台',hero_title:'灯笼之下<br>世界的<em>故事</em><br>在此汇聚',hero_desc:'来自480家出版社、12种语言的多元文化图书，由馆员审核后供应。报价单、MARC数据与加工一站完成。',hero_cta1:'检索·采购',hero_cta2:'进入灯笼展厅',stat_lang:'支持语言',stat_books:'收录图书',stat_lib:'供应馆',hero_hint:'移动鼠标让灯笼摇曳 · 点击迸出火星',
 notice:'2026下半年公共图书馆多元文化资料采购支持项目 — 9月底报价截止',notice_link:'开具报价单',
 cur_eyebrow:'策展 · Curated Exhibitions',cur_title:'如灯笼般悬挂的本月策展',cur_desc:'三种不同展示形式的策展。3D灯笼展厅可拖动环视。',
 hall_eyebrow:'3D 灯笼展厅',hall_desc:'拖动旋转回廊，点击灯笼（封面）查看书目信息。',
 new_eyebrow:'新书 · New Arrivals',new_title:'本月到馆新书',view_active:'动态',view_list:'书目列表',
 lib1_t:'馆员审核图书',lib1_d:'仅收录经12位在职馆员审核内容、翻译与装订质量的图书。',lib2_t:'提供 MARC/书目数据',lib2_d:'随书提供 KORMARC 数据及标签、条码加工。',lib3_t:'即时开具公文报价单',lib3_d:'已含机构折扣的报价单可直接导出PDF附于公文。',
 search_eyebrow:'图书检索 · 采购',search_title:'以馆员标准检索多元文化图书',search_ph:'书名、作者、ISBN',f_lang:'语言',f_age:'适读年龄',f_stock:'供应状态',f_reset:'重置筛选',sort_new:'最新到馆',sort_price:'价格',sort_title:'书名',result_count:'{n} 册',
 age_child:'幼儿·小学',age_teen:'青少年',age_adult:'成人·馆员',stock_ok:'即时供应',stock_wait:'待到货',
 curpage_title:'全部策展',type_hall:'3D 灯笼展厅',type_stall:'夜市摊位',type_sky:'天灯',books_n:'收录 {n} 册',
 c1_t:'世界绘本双年展获奖作',c1_d:'BIB、博洛尼亚拉加齐奖获奖作原版+译本套装。',c2_t:'亚洲的节日与灯笼',c2_d:'燃灯会、元宵、宋干、祭典 — 以节日认识邻国文化。',c3_t:'多元家庭家长·馆员必读',c3_d:'生活韩语、馆藏发展指南、青少年文学。',
 cart_eyebrow:'报价篮',cart_title:'供应报价篮',cart_summary:'报价摘要',cart_org:'机构类型',org_public:'公共图书馆（9折）',org_school:'学校图书馆（9折）',org_multi:'多元文化家庭支援中心（85折）',org_personal:'个人购买（无折扣）',cart_sub:'定价合计',cart_disc:'机构折扣',cart_total:'预计供应金额',cart_note:'图书免增值税。运费与加工费另议。',cart_quote:'开具公文报价单',cart_clear:'清空报价篮',cart_empty:'报价篮为空，请检索并加入图书。',
 back:'返回列表',add:'加入报价篮',added:'已加入报价篮',removed:'已从报价篮移除',cleared:'已清空报价篮',quote_done:'打开报价单（PDF）打印窗口',
 b_isbn:'ISBN',b_lang:'语言',b_country:'原产国',b_age:'对象',b_pub:'出版社',b_year:'出版年',b_kdc:'KDC',b_pages:'页数',b_stock:'供应',price_unit:'韩元',qty:'数量',footer_desc:'多元文化图书馆供应 · 与馆员共建世界书架',th_title:'书名',th_lang:'语言',th_age:'对象',th_pub:'出版社',th_price:'定价',th_stock:'供应',th_act:''}
};
/* ---- v10 overrides + JA ---- */
const OV={
ko:{brand:'팝업북 시티',brand_sub:'Pop-up Book City · 어린이 다문화 도서 납품',hero_eyebrow:'어린이·다문화 도서관 납품 플랫폼',hero_title:'책으로 지은<br><span>알록달록</span><br>세계 마을',hero_desc:'빌딩 하나가 책 한 권. 12개 언어의 그림책과 이중언어 동화를 사서가 검수해 납품합니다. 연령별 필터, 견적서, MARC 데이터까지 놀이처럼 쉽게.',hero_cta1:'연령별 도서 찾기',hero_cta2:'회전 전시대 보기',hero_hint:'마우스로 도시를 둘러보고 · 빌딩을 클릭하면 통통!',
 notice:'2026 하반기 어린이도서관 다문화자료 구입 지원사업 — 9월 30일 견적 마감 · 보드북·빅북 특가',notice_link:'견적서 발급',cur_eyebrow:'기획전 · Exhibitions',cur_title:'이달의 놀이 같은 기획전',cur_desc:'회전 전시대, 팝업북 펼침, 책 빌딩 거리 — 세 가지 전시 형태.',turn_eyebrow:'3D Turntable Pedestal',turn_desc:'전시대가 천천히 돌아갑니다. 드래그로 돌리고, 정면 책을 클릭하면 서지정보.',
 new_title:'이번 달 도착한 신간',view_active:'통통 뷰',view_list:'서지 목록',lib1_t:'연령 적합성 검수',lib1_d:'어린이 사서 12명이 연령 적합성·번역 품질·제본 안전성을 검수합니다.',lib2_t:'KORMARC · 장비 작업',lib2_d:'서지 데이터, 라벨, 바코드, 비닐 커버링까지 납품과 함께.',lib3_t:'공문용 견적서',lib3_d:'기관 할인 반영 견적서를 PDF로 즉시 출력해 기안에 첨부.',
 search_title:'연령과 언어로 고르는 그림책',search_ph:'제목, 원제, 출판사, ISBN',sort_new:'최신 도착순',type_turn:'회전 전시대',type_pop:'팝업북 펼침',type_street:'책 빌딩 거리',curpage_title:'기획전 전체',org_public:'공공·어린이도서관 (12% 할인)',footer_desc:'어린이·다문화 도서관 납품 · 책으로 짓는 세계 마을',age_child:'유아·초등',age_teen:'청소년',age_adult:'성인·사서',floors:'{n}층'},
en:{brand:'Pop-up Book City',brand_sub:'Children\'s multicultural book supply',hero_eyebrow:'Children\'s & multicultural library supply',hero_title:'A colourful<br><span>world village</span><br>built from books',hero_desc:'One building, one book. Picture books and bilingual tales in 12 languages, vetted by children\'s librarians. Age filters, quotations and MARC data, as easy as play.',hero_cta1:'Find books by age',hero_cta2:'See the turntable',hero_hint:'Move the mouse to look around · click a building to bounce it!',
 notice:'2026 H2 children\'s library multicultural grant — quotation deadline Sep 30 · board books & big books on offer',notice_link:'Issue quotation',cur_eyebrow:'Exhibitions',cur_title:'This month\'s playful exhibitions',cur_desc:'Turntable pedestal, pop-up book spread, book-building street — three display forms.',turn_eyebrow:'3D Turntable Pedestal',turn_desc:'The pedestal turns slowly. Drag to spin; click the front book for its record.',
 new_title:'Arrived this month',view_active:'Bouncy view',view_list:'Record list',lib1_t:'Age-appropriateness review',lib1_d:'12 children\'s librarians check age fit, translation quality and binding safety.',lib2_t:'KORMARC · processing',lib2_d:'Records, labels, barcodes and plastic covering delivered with the books.',lib3_t:'Official quotation',lib3_d:'PDF quotation with institutional discount, ready to attach.',
 search_title:'Picture books by age and language',search_ph:'Title, original title, publisher, ISBN',sort_new:'Newest arrivals',type_turn:'Turntable pedestal',type_pop:'Pop-up spread',type_street:'Book-building street',curpage_title:'All exhibitions',org_public:'Public / children\'s library (12% off)',footer_desc:'Children\'s & multicultural library supply · a world village built from books',floors:'{n} floors'},
vi:{brand:'Thành phố Sách Nổi',brand_sub:'Cung ứng sách thiếu nhi đa văn hóa',hero_eyebrow:'Nền tảng cung ứng thư viện thiếu nhi · đa văn hóa',hero_title:'Ngôi làng thế giới<br><span>rực rỡ sắc màu</span><br>xây bằng sách',hero_desc:'Mỗi tòa nhà là một cuốn sách. Sách tranh và truyện song ngữ 12 thứ tiếng do thủ thư thiếu nhi thẩm định. Lọc theo tuổi, báo giá, dữ liệu MARC dễ như chơi.',hero_cta1:'Tìm sách theo tuổi',hero_cta2:'Xem giá xoay',hero_hint:'Di chuột ngắm thành phố · nhấp tòa nhà để nảy!',
 notice:'Dự án hỗ trợ tài liệu đa văn hóa cho thư viện thiếu nhi nửa cuối 2026 — hạn báo giá 30/9 · ưu đãi sách bìa cứng, sách khổ lớn',notice_link:'Phát hành báo giá',cur_eyebrow:'Triển lãm',cur_title:'Triển lãm vui nhộn tháng này',cur_desc:'Giá xoay, sách nổi mở trang, phố tòa nhà sách — ba hình thức trưng bày.',turn_eyebrow:'Giá xoay 3D',turn_desc:'Giá xoay từ từ. Kéo để xoay; nhấp sách phía trước để xem thông tin.',
 new_title:'Sách đến tháng này',view_active:'Chế độ nảy',view_list:'Danh mục',lib1_t:'Thẩm định phù hợp lứa tuổi',lib1_d:'12 thủ thư thiếu nhi kiểm tra độ phù hợp lứa tuổi, chất lượng dịch và an toàn đóng gáy.',lib2_t:'KORMARC · xử lý kỹ thuật',lib2_d:'Dữ liệu, nhãn, mã vạch, bọc nhựa giao kèm sách.',lib3_t:'Báo giá chính thức',lib3_d:'Báo giá PDF có chiết khấu cơ quan, sẵn sàng đính kèm.',
 search_title:'Sách tranh theo tuổi và ngôn ngữ',search_ph:'Tên sách, tên gốc, NXB, ISBN',sort_new:'Mới đến',type_turn:'Giá xoay',type_pop:'Sách nổi mở trang',type_street:'Phố tòa nhà sách',curpage_title:'Tất cả triển lãm',org_public:'Thư viện công cộng/thiếu nhi (giảm 12%)',footer_desc:'Cung ứng thư viện thiếu nhi đa văn hóa · làng thế giới xây bằng sách',floors:'{n} tầng'},
zh:{brand:'立体书之城',brand_sub:'儿童多元文化图书供应',hero_eyebrow:'儿童·多元文化图书馆供应平台',hero_title:'用书建成的<br><span>五彩缤纷</span><br>世界村',hero_desc:'一栋楼就是一本书。12种语言的绘本与双语童话，由儿童馆员审核供应。年龄筛选、报价单、MARC数据，像游戏一样简单。',hero_cta1:'按年龄找书',hero_cta2:'查看旋转展台',hero_hint:'移动鼠标环视城市 · 点击楼房会弹跳！',
 notice:'2026下半年儿童图书馆多元文化资料采购支持项目 — 9月30日报价截止 · 纸板书·大开本特惠',notice_link:'开具报价单',cur_eyebrow:'策展',cur_title:'本月像游戏一样的策展',cur_desc:'旋转展台、立体书展开、书楼街道 — 三种展示形式。',turn_eyebrow:'3D 旋转展台',turn_desc:'展台缓慢旋转。拖动旋转，点击正面图书查看书目。',
 new_title:'本月到馆新书',view_active:'弹跳视图',view_list:'书目列表',lib1_t:'年龄适宜性审核',lib1_d:'12位儿童馆员审核年龄适宜性、翻译质量与装订安全。',lib2_t:'KORMARC · 加工',lib2_d:'书目数据、标签、条码、塑封随书提供。',lib3_t:'公文报价单',lib3_d:'含机构折扣的PDF报价单即时导出。',
 search_title:'按年龄与语言挑选绘本',search_ph:'书名、原名、出版社、ISBN',sort_new:'最新到馆',type_turn:'旋转展台',type_pop:'立体书展开',type_street:'书楼街道',curpage_title:'全部策展',org_public:'公共·儿童图书馆（9折）',footer_desc:'儿童·多元文化图书馆供应 · 用书建成的世界村',floors:'{n} 层'}
};
I18N.ja=Object.assign({},I18N.en,{brand:'ポップアップ・ブックシティ',brand_sub:'児童・多文化図書の納品',nav_home:'ホーム',nav_search:'図書検索',nav_curation:'企画展',nav_cart:'見積かご',hero_eyebrow:'児童・多文化図書館 納品プラットフォーム',hero_title:'本で建てた<br><span>色とりどりの</span><br>世界の村',hero_desc:'ビル一棟が本一冊。12言語の絵本とバイリンガル童話を司書が検収して納品します。年齢別フィルター、見積書、MARCデータまで遊ぶように簡単に。',hero_cta1:'年齢別で探す',hero_cta2:'回転展示台を見る',hero_hint:'マウスで街を見渡し · ビルをクリックすると弾みます！',notice:'2026年下半期 児童図書館 多文化資料購入支援事業 — 9月30日見積締切 · ボードブック特価',notice_link:'見積書を発行',cur_eyebrow:'企画展',cur_title:'今月の遊ぶような企画展',cur_desc:'回転展示台、ポップアップ見開き、本のビル街 — 三つの展示形式。',turn_eyebrow:'3D 回転展示台',turn_desc:'展示台がゆっくり回ります。ドラッグで回し、正面の本をクリックすると書誌情報へ。',new_eyebrow:'新刊',new_title:'今月届いた新刊',view_active:'ぽんぽんビュー',view_list:'書誌リスト',lib1_t:'年齢適合性の検収',lib1_d:'児童司書12名が年齢適合性・翻訳品質・製本の安全性を検収します。',lib2_t:'KORMARC · 装備作業',lib2_d:'書誌データ、ラベル、バーコード、ビニールカバーまで納品と一緒に。',lib3_t:'公文用見積書',lib3_d:'機関割引を反映した見積書をPDFで即時出力。',search_eyebrow:'図書検索 · 選書',search_title:'年齢と言語で選ぶ絵本',search_ph:'書名、原題、出版社、ISBN',f_lang:'言語',f_age:'対象年齢',f_stock:'納品状況',f_reset:'フィルター初期化',sort_new:'新着順',sort_price:'価格順',sort_title:'書名順',result_count:'{n}冊',age_child:'幼児・小学生',age_teen:'中高生',age_adult:'大人・司書',stock_ok:'即納',stock_wait:'入荷待ち',type_turn:'回転展示台',type_pop:'ポップアップ見開き',type_street:'本のビル街',books_n:'{n}冊収録',curpage_title:'企画展一覧',c1_t:'世界絵本ビエンナーレ受賞作',c1_d:'BIB・ボローニャ受賞作の原書+翻訳セット。',c2_t:'アジアの祭りと灯り',c2_d:'燃灯会、元宵、ソンクラン、祭り — 祭りで学ぶ隣国の文化。',c3_t:'多文化家庭の保護者・司書 必読書',c3_d:'生活韓国語、蔵書開発ガイド、YA文学。',cart_eyebrow:'見積かご',cart_title:'納品見積かご',cart_summary:'見積概要',cart_org:'機関種別',org_public:'公共・児童図書館（12%割引）',org_school:'学校図書館（10%割引）',org_multi:'多文化家族支援センター（15%割引）',org_personal:'個人購入（0%）',cart_sub:'定価合計',cart_disc:'機関割引',cart_total:'納品予定金額',cart_note:'図書は非課税。送料・装備費は別途。',cart_quote:'公文用見積書を発行',cart_clear:'かごを空にする',cart_empty:'かごは空です。図書を検索して追加してください。',back:'一覧へ',add:'かごに入れる',added:'かごに入れました',removed:'かごから削除しました',cleared:'かごを空にしました',quote_done:'見積書（PDF）印刷ウィンドウを開きます',b_isbn:'ISBN',b_lang:'言語',b_country:'原産国',b_age:'対象',b_pub:'出版社',b_year:'刊行',b_kdc:'KDC',b_pages:'ページ',b_stock:'納品',price_unit:'ウォン',footer_desc:'児童・多文化図書館の納品 · 本で建てる世界の村',th_title:'書名',th_lang:'言語',th_age:'対象',th_pub:'出版社',th_price:'定価',th_stock:'納品',floors:'{n}階'});
Object.keys(OV).forEach(l=>Object.assign(I18N[l],OV[l]));
CURATIONS[0].type='turn';CURATIONS[1].type='pop';CURATIONS[2].type='street';

let lang=localStorage.getItem('v10_lang')||'ko';
const t=(k,vars)=>{let s=(I18N[lang]&&I18N[lang][k])||I18N.ko[k]||k;if(vars)Object.keys(vars).forEach(v=>s=s.replace('{'+v+'}',vars[v]));return s;};
function applyI18n(){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>el.innerHTML=t(el.dataset.i18n));document.querySelectorAll('[data-i18n-ph]').forEach(el=>el.placeholder=t(el.dataset.i18nPh));document.querySelectorAll('#lang-switch button').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));renderAll();}
document.querySelectorAll('#lang-switch button').forEach(b=>b.addEventListener('click',()=>{lang=b.dataset.lang;localStorage.setItem('v10_lang',lang);applyI18n();}));
const $=s=>document.querySelector(s);const fmt=n=>n.toLocaleString('ko-KR')+' '+t('price_unit');const byId=id=>BOOKS.find(b=>b.id===+id);
function coverHTML(b){return `<div class="book-cover" style="background:linear-gradient(150deg,${b.color[0]},${b.color[1]})"><div class="t">${b.title}</div><div class="l">${t('age_'+b.age)}</div></div>`;}
function stockTag(b){return `<span class="tag ${b.stock}">${t('stock_'+b.stock)}</span>`;}
function toast(m){const el=$('#toast');el.textContent=m;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),1800);}

/* FX: squash + confetti */
const fx=$('#fx-canvas'),fctx=fx.getContext('2d');let confetti=[];const CONF=['#ff7a59','#3d7bff','#ffc843','#7bd389','#b784ff','#ff9ec6'];
function resizeFx(){fx.width=innerWidth;fx.height=innerHeight;}resizeFx();addEventListener('resize',resizeFx);
function burst(x,y,n=26){for(let i=0;i<n;i++){const a=-Math.PI/2+(Math.random()-.5)*2.2,s=4+Math.random()*7;confetti.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:1,w:6+Math.random()*6,h:8+Math.random()*8,r:Math.random()*6,vr:(Math.random()-.5)*.3,c:CONF[i%CONF.length]});}}
(function loop(){fctx.clearRect(0,0,fx.width,fx.height);confetti=confetti.filter(p=>p.life>0);for(const p of confetti){p.x+=p.vx;p.y+=p.vy;p.vy+=.35;p.vx*=.98;p.r+=p.vr;p.life-=.014;fctx.save();fctx.globalAlpha=Math.max(p.life,0);fctx.translate(p.x,p.y);fctx.rotate(p.r);fctx.fillStyle=p.c;fctx.fillRect(-p.w/2,-p.h/2,p.w,p.h);fctx.restore();}requestAnimationFrame(loop);})();
document.addEventListener('click',e=>{const b=e.target.closest('.pop-btn,.btn,.chip,.mini-btn,.turn-tabs button,.view-toggle button');if(!b)return;b.classList.remove('squash');void b.offsetWidth;b.classList.add('squash');burst(e.clientX,e.clientY,b.classList.contains('btn-primary')||b.classList.contains('cart-btn')?40:18);});

/* CART */
let cart=JSON.parse(localStorage.getItem('v10_cart')||'{}');
function saveCart(){localStorage.setItem('v10_cart',JSON.stringify(cart));$('#cart-count').textContent=Object.values(cart).reduce((a,b)=>a+b,0);const cb=$('#cart-btn');cb.classList.remove('bounce');void cb.offsetWidth;cb.classList.add('bounce');}
function addToCart(id,q=1){cart[id]=(cart[id]||0)+q;saveCart();toast(t('added'));renderCart();}
function removeFromCart(id){delete cart[id];saveCart();toast(t('removed'));renderCart();}
function setQty(id,q){q=Math.max(1,Math.min(999,+q||1));cart[id]=q;saveCart();renderCart();}
document.addEventListener('click',e=>{const a=e.target.closest('[data-add]');if(a){e.preventDefault();e.stopPropagation();addToCart(a.dataset.add);}});
function renderCart(){const wrap=$('#cart-items');const ids=Object.keys(cart);wrap.innerHTML=ids.length?ids.map(id=>{const b=byId(id);return `<div class="cart-row">${coverHTML(b)}<div><h4>${b.title}</h4><div class="muted"><span class="isbn">${b.isbn}</span> · ${LANG_NAMES[b.lang]} · ${t('age_'+b.age)}</div>${stockTag(b)}</div><div class="qty"><button data-q="-1" data-id="${id}">−</button><input value="${cart[id]}" data-qin="${id}"><button data-q="1" data-id="${id}">+</button></div><b style="color:var(--coral);font-family:var(--disp)">${fmt(b.price*cart[id])}</b><button class="del" data-del="${id}"><span class="material-symbols-rounded">close</span></button></div>`;}).join(''):`<div class="cart-empty">${t('cart_empty')}</div>`;const rate=+$('#org-type').value;const sub=ids.reduce((s,id)=>s+byId(id).price*cart[id],0);const disc=Math.round(sub*rate);$('#sum-sub').textContent=fmt(sub);$('#sum-disc').textContent='− '+fmt(disc);$('#sum-total').textContent=fmt(sub-disc);}
$('#cart-items').addEventListener('click',e=>{const q=e.target.closest('[data-q]');if(q)setQty(q.dataset.id,cart[q.dataset.id]+ +q.dataset.q);const d=e.target.closest('[data-del]');if(d)removeFromCart(d.dataset.del);});
$('#cart-items').addEventListener('change',e=>{if(e.target.dataset.qin)setQty(e.target.dataset.qin,e.target.value);});
$('#org-type').addEventListener('change',renderCart);$('#btn-clear').addEventListener('click',()=>{cart={};saveCart();renderCart();toast(t('cleared'));});
$('#btn-quote').addEventListener('click',()=>{toast(t('quote_done'));const ids=Object.keys(cart);if(!ids.length)return;const rate=+$('#org-type').value;const sub=ids.reduce((s,id)=>s+byId(id).price*cart[id],0);const w=window.open('','_blank');w.document.write(`<html><head><meta charset="utf-8"><title>견적서</title><style>body{font-family:sans-serif;padding:40px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #999;padding:8px;font-size:13px}h1{letter-spacing:.3em}</style></head><body><h1>견 적 서</h1><p>팝업북 시티 · 어린이 다문화 도서 납품 · ${new Date().toLocaleDateString('ko-KR')}</p><table><tr><th>No</th><th>서명</th><th>ISBN</th><th>대상</th><th>정가</th><th>수량</th><th>금액</th></tr>${ids.map((id,i)=>{const b=byId(id);return `<tr><td>${i+1}</td><td>${b.title}</td><td>${b.isbn}</td><td>${t('age_'+b.age)}</td><td>${b.price.toLocaleString()}</td><td>${cart[id]}</td><td>${(b.price*cart[id]).toLocaleString()}</td></tr>`}).join('')}</table><p>정가 합계 ${sub.toLocaleString()}원 · 기관 할인 ${rate*100}% · <b>납품 금액 ${(sub-Math.round(sub*rate)).toLocaleString()}원</b></p><script>window.print()<\/script></body></html>`);w.document.close();});

/* ROUTER */
let detailScene=null,curScene=null;
function route(){const h=(location.hash||'#home').slice(1);const [page,param]=h.split('/');document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));($('#page-'+page)||$('#page-home')).classList.remove('hidden');document.querySelectorAll('.main-nav a').forEach(a=>a.classList.toggle('active',a.dataset.route===page));window.scrollTo({top:0});if(page==='detail')renderDetail(param);if(page==='curation')renderCurationPage(param);if(page==='cart')renderCart();if(page==='search')renderResults();}
addEventListener('hashchange',route);

/* CURATION cards */
function curVisual(c){const books=BOOKS.filter(b=>b.cur.includes(c.id));
 if(c.type==='turn')return `<div class="cur-visual"><div class="cv-bg"></div><div class="mini-turn"><div>${books.slice(0,6).map((b,i)=>`<i style="background:linear-gradient(${b.color[0]},${b.color[1]});transform:rotateY(${i*60}deg) translateZ(70px)"></i>`).join('')}</div></div></div>`;
 if(c.type==='pop')return `<div class="cur-visual"><div class="cv-bg"></div><div class="mini-pop"><i></i><i></i><b style="background:${books[0].color[0]}"></b></div></div>`;
 return `<div class="cur-visual"><div class="cv-bg"></div><div class="mini-street">${books.slice(0,8).map((b,i)=>`<i style="height:${50+(i*37)%70}px;background:${b.color[0]}"></i>`).join('')}</div></div>`;}
function curCard(c){const n=BOOKS.filter(b=>b.cur.includes(c.id)).length;return `<a href="#curation/${c.id}" class="cur-card pop-btn">${curVisual(c)}<span class="type">${t('type_'+c.type)}</span><h3>${t(c.titleKey)}</h3><p>${t(c.descKey)}</p><span class="count">${t('books_n',{n})}</span></a>`;}
function renderHomeCurations(){$('#home-curations').innerHTML=CURATIONS.map(curCard).join('');$('#cur-list').innerHTML=CURATIONS.map(curCard).join('');}

/* NEW books */
function renderNew(){const news=BOOKS.filter(b=>b.new);$('#new-active').innerHTML=news.map((b,i)=>`<a href="#detail/${b.id}" class="bounce-card" style="animation-delay:${i*.07}s">${coverHTML(b)}<h4>${b.title}</h4><div class="meta">${LANG_NAMES[b.lang]} · ${b.pub}</div><span class="age-badge">${t('age_'+b.age)}</span><div class="price">${fmt(b.price)}</div></a>`).join('');
 $('#new-list').innerHTML=`<table><thead><tr><th>ISBN</th><th>${t('th_title')}</th><th>${t('th_age')}</th><th>${t('th_lang')}</th><th>${t('th_pub')}</th><th>${t('th_price')}</th><th>${t('th_stock')}</th><th></th></tr></thead><tbody>${news.map(b=>`<tr><td class="isbn">${b.isbn}</td><td><a href="#detail/${b.id}"><b>${b.title}</b><br><span class="muted">${b.orig}</span></a></td><td>${t('age_'+b.age)}</td><td>${LANG_NAMES[b.lang]}</td><td>${b.pub}</td><td>${fmt(b.price)}</td><td>${stockTag(b)}</td><td><button class="mini-btn" data-add="${b.id}">${t('add')}</button></td></tr>`).join('')}</tbody></table>`;}
$('#new-toggle').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;document.querySelectorAll('#new-toggle button').forEach(x=>x.classList.toggle('active',x===b));$('#new-active').classList.toggle('hidden',b.dataset.view!=='active');$('#new-list').classList.toggle('hidden',b.dataset.view!=='list');if(b.dataset.view==='active')renderNew();});

/* SEARCH */
const filters={lang:new Set(),age:new Set(),stock:new Set()};
function renderFilterChips(){const langs=[...new Set(BOOKS.map(b=>b.lang))];$('#f-lang').innerHTML=langs.map(l=>`<button class="chip ${filters.lang.has(l)?'active':''}" data-f="lang" data-v="${l}">${LANG_NAMES[l]}</button>`).join('');$('#f-age').innerHTML=['child','teen','adult'].map(a=>`<button class="chip ${filters.age.has(a)?'active':''}" data-f="age" data-v="${a}">${t('age_'+a)}</button>`).join('');$('#f-stock').innerHTML=['ok','wait'].map(s=>`<button class="chip ${filters.stock.has(s)?'active':''}" data-f="stock" data-v="${s}">${t('stock_'+s)}</button>`).join('');}
$('.filters').addEventListener('click',e=>{const c=e.target.closest('.chip');if(!c)return;const set=filters[c.dataset.f];set.has(c.dataset.v)?set.delete(c.dataset.v):set.add(c.dataset.v);renderFilterChips();renderResults();});
$('#f-reset').addEventListener('click',()=>{Object.values(filters).forEach(s=>s.clear());$('#q').value='';renderFilterChips();renderResults();});
$('#q').addEventListener('input',renderResults);$('#sort').addEventListener('change',renderResults);
function renderResults(){const q=$('#q').value.trim().toLowerCase();let list=BOOKS.filter(b=>(!q||b.title.toLowerCase().includes(q)||b.orig.toLowerCase().includes(q)||b.isbn.includes(q)||b.pub.toLowerCase().includes(q))&&(!filters.lang.size||filters.lang.has(b.lang))&&(!filters.age.size||filters.age.has(b.age))&&(!filters.stock.size||filters.stock.has(b.stock)));const s=$('#sort').value;if(s==='price')list.sort((a,b)=>a.price-b.price);else if(s==='title')list.sort((a,b)=>a.title.localeCompare(b.title));else list.sort((a,b)=>b.year-a.year||b.id-a.id);$('#result-count').textContent=t('result_count',{n:list.length});$('#results').innerHTML=list.map(b=>`<a href="#detail/${b.id}" class="res-card">${coverHTML(b)}<div><h4>${b.title}</h4><div class="meta">${b.orig}<br>${LANG_NAMES[b.lang]} · ${t('age_'+b.age)} · ${b.pub}<br><span class="isbn">${b.isbn}</span></div><div class="price">${fmt(b.price)}</div>${stockTag(b)} <button class="mini-btn" data-add="${b.id}">${t('add')}</button></div></a>`).join('');}

/* THREE helpers */
function coverTexture(b){const c=document.createElement('canvas');c.width=256;c.height=360;const g=c.getContext('2d');const gr=g.createLinearGradient(0,0,256,360);gr.addColorStop(0,b.color[0]);gr.addColorStop(1,b.color[1]);g.fillStyle=gr;g.fillRect(0,0,256,360);g.strokeStyle='#fff';g.lineWidth=10;g.strokeRect(0,0,256,360);g.fillStyle='#fff';g.font='900 26px "Noto Sans KR", sans-serif';g.shadowColor='rgba(0,0,0,.35)';g.shadowBlur=6;const words=b.title.split(' ');let line='',y=54;for(const w of words){const test=line?line+' '+w:w;if(g.measureText(test).width>205){g.fillText(line,26,y);line=w;y+=32;}else line=test;}g.fillText(line,26,y);return new THREE.CanvasTexture(c);}
function buildingTexture(b){const c=document.createElement('canvas');c.width=128;c.height=256;const g=c.getContext('2d');g.fillStyle=b.color[0];g.fillRect(0,0,128,256);g.fillStyle='rgba(255,255,255,.45)';for(let y=18;y<240;y+=30)for(let x=14;x<120;x+=30)g.fillRect(x,y,16,18);return new THREE.CanvasTexture(c);}
function fitRenderer(r,cv){const w=cv.clientWidth,h=cv.clientHeight;r.setSize(w,h,false);return w/h;}
function bookMesh(b,w=1.4,h=2,d=.2){const paper=new THREE.MeshStandardMaterial({color:0xffffff});return new THREE.Mesh(new THREE.BoxGeometry(w,h,d),[new THREE.MeshStandardMaterial({color:b.color[0]}),paper,paper,paper,new THREE.MeshStandardMaterial({map:coverTexture(b),roughness:.5}),new THREE.MeshStandardMaterial({color:b.color[1]})]);}

/* HERO: pop-up book city */
(function hero(){const cv=$('#hero-canvas');const renderer=new THREE.WebGLRenderer({canvas:cv,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
 const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.set(6,7,18);
 scene.add(new THREE.HemisphereLight(0xffffff,0xbfe9ff,.9));const dl=new THREE.DirectionalLight(0xffffff,.9);dl.position.set(8,14,8);dl.castShadow=true;dl.shadow.mapSize.set(2048,2048);dl.shadow.camera.left=-20;dl.shadow.camera.right=20;dl.shadow.camera.top=20;dl.shadow.camera.bottom=-20;scene.add(dl);
 const ground=new THREE.Mesh(new THREE.CylinderGeometry(15,15,.6,64),new THREE.MeshStandardMaterial({color:0x8ed19a,roughness:1}));ground.position.y=-.3;ground.receiveShadow=true;scene.add(ground);
 const city=new THREE.Group();city.position.x=4;scene.add(city);const bld=[];
 BOOKS.forEach((b,i)=>{const gx=(i%5)-2,gz=Math.floor(i/5)-1;const h=2+((b.id*7)%5)*.9;const w=1.3+((b.id*3)%3)*.2;const tex=buildingTexture(b);const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,w),[tex,tex,new THREE.MeshStandardMaterial({color:0xffffff}),new THREE.MeshStandardMaterial({color:b.color[0]}),tex,tex].map(x=>x.isMaterial?x:new THREE.MeshStandardMaterial({map:x,roughness:.7})));m.position.set(gx*2.4+(gz%2)*.6,h/2,gz*2.4);m.castShadow=true;m.receiveShadow=true;m.scale.y=0;m.userData={book:b,h,ph:Math.random()*6};city.add(m);bld.push(m);
  const roof=new THREE.Mesh(new THREE.ConeGeometry(w*.75,.8,4),new THREE.MeshStandardMaterial({color:b.color[1]}));roof.rotation.y=Math.PI/4;roof.position.y=h/2+.4;roof.castShadow=true;m.add(roof);roof.scale.setScalar(1/1);});
 // pop-up rise
 bld.forEach((m,i)=>gsap.to(m.scale,{y:1,duration:1,delay:.3+i*.08,ease:'elastic.out(1,.6)'}));
 // clouds
 for(let i=0;i<6;i++){const cl=new THREE.Group();for(let j=0;j<3;j++){const s=new THREE.Mesh(new THREE.SphereGeometry(.6+Math.random()*.5,12,12),new THREE.MeshStandardMaterial({color:0xffffff}));s.position.set(j*.8-.8,Math.random()*.3,0);cl.add(s);}cl.position.set(-14+Math.random()*28,7+Math.random()*3,-6+Math.random()*4);cl.userData={s:.01+Math.random()*.02};scene.add(cl);cl.userData.cloud=true;}
 const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let hover=null,mx=0,my=0;
 cv.addEventListener('mousemove',e=>{const r=cv.getBoundingClientRect();mx=(e.clientX-r.left)/r.width*2-1;my=-((e.clientY-r.top)/r.height*2-1);mouse.set(mx,my);ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(bld)[0];hover=hit?hit.object:null;cv.style.cursor=hover?'pointer':'default';});
 cv.addEventListener('click',e=>{if(!hover)return;const m=hover;gsap.fromTo(m.scale,{x:1.25,y:.75,z:1.25},{x:1,y:1,z:1,duration:.8,ease:'elastic.out(1,.4)'});burst(e.clientX,e.clientY,30);setTimeout(()=>location.hash='#detail/'+m.userData.book.id,500);});
 const clock=new THREE.Clock();(function anim(){requestAnimationFrame(anim);const t0=clock.getElapsedTime();camera.aspect=fitRenderer(renderer,cv);camera.updateProjectionMatrix();city.rotation.y+=((mx*.5)-city.rotation.y)*.04;camera.position.y+=((7-my*2)-camera.position.y)*.04;camera.lookAt(4,1.5,0);scene.children.forEach(c=>{if(c.userData.cloud){c.position.x+=c.userData.s;if(c.position.x>16)c.position.x=-16;}});bld.forEach(m=>{if(m===hover)m.position.y=m.userData.h/2+Math.abs(Math.sin(t0*8))*.3;else m.position.y+=((m.userData.h/2)-m.position.y)*.2;});renderer.render(scene,camera);})();})();

/* TURNTABLE (three.js) */
function makeTurntable(cv,tip,books){const renderer=new THREE.WebGLRenderer({canvas:cv,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(36,1,.1,100);camera.position.set(0,4.5,13);camera.lookAt(0,.8,0);
 scene.add(new THREE.HemisphereLight(0xffffff,0xbfe9ff,.95));const dl=new THREE.DirectionalLight(0xffffff,.8);dl.position.set(6,12,8);dl.castShadow=true;dl.shadow.mapSize.set(2048,2048);scene.add(dl);
 const base=new THREE.Group();scene.add(base);const R=4.2;
 const ped=new THREE.Mesh(new THREE.CylinderGeometry(R+1,R+1.3,.5,64),new THREE.MeshStandardMaterial({color:0xffffff}));ped.position.y=-.25;ped.receiveShadow=true;base.add(ped);
 const rim=new THREE.Mesh(new THREE.TorusGeometry(R+1.15,.12,12,80),new THREE.MeshStandardMaterial({color:0xffc843}));rim.rotation.x=Math.PI/2;rim.position.y=0;base.add(rim);
 const meshes=[];books.forEach((b,i)=>{const a=i/books.length*Math.PI*2;const m=bookMesh(b,1.6,2.24,.22);m.position.set(Math.sin(a)*R,1.12,Math.cos(a)*R);m.lookAt(Math.sin(a)*R*2,1.12,Math.cos(a)*R*2);m.castShadow=true;m.userData={book:b,a};base.add(m);meshes.push(m);const disc=new THREE.Mesh(new THREE.CylinderGeometry(.9,.9,.12,32),new THREE.MeshStandardMaterial({color:b.color[1]}));disc.position.set(Math.sin(a)*R,.06,Math.cos(a)*R);base.add(disc);});
 let rot=0,vel=0,drag=false,lx=0,moved=0;const ray=new THREE.Raycaster(),mouse=new THREE.Vector2();let hover=null;
 cv.addEventListener('mousedown',e=>{drag=true;lx=e.clientX;moved=0;cv.style.cursor='grabbing';});addEventListener('mouseup',()=>{drag=false;cv.style.cursor='grab';});
 cv.addEventListener('mousemove',e=>{if(drag){const dx=e.clientX-lx;vel=dx*.005;rot+=vel;lx=e.clientX;moved+=Math.abs(dx);}const r=cv.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height*2-1));ray.setFromCamera(mouse,camera);const hit=ray.intersectObjects(meshes)[0];hover=hit?hit.object:null;if(hover){tip.style.opacity=1;tip.style.left=(e.clientX-r.left+14)+'px';tip.style.top=(e.clientY-r.top+14)+'px';tip.innerHTML=`<b>${hover.userData.book.title}</b>${t('age_'+hover.userData.book.age)} · ${fmt(hover.userData.book.price)}`;if(!drag)cv.style.cursor='pointer';}else{tip.style.opacity=0;if(!drag)cv.style.cursor='grab';}});
 cv.addEventListener('click',()=>{if(hover&&moved<6)location.hash='#detail/'+hover.userData.book.id;});
 let alive=true;const clock=new THREE.Clock();(function anim(){if(!alive)return;requestAnimationFrame(anim);const t0=clock.getElapsedTime();camera.aspect=fitRenderer(renderer,cv);camera.updateProjectionMatrix();if(!drag){vel*=.95;rot+=vel+.004;}base.rotation.y=rot;meshes.forEach(m=>{const wa=(m.userData.a+rot)%(Math.PI*2);const front=Math.cos(wa);const s=1+Math.max(0,front)*.25+(m===hover?.12:0);m.scale.setScalar(s);m.position.y=1.12*s+Math.sin(t0*2+m.userData.a)*.05;});renderer.render(scene,camera);})();return{dispose(){alive=false;renderer.dispose();}};}
let homeTurn=null;
function initHomeTurn(id){if(homeTurn)homeTurn.dispose();const c=CURATIONS.find(x=>x.id===id);$('#turn-title').textContent=t(c.titleKey);homeTurn=makeTurntable($('#turn-canvas'),$('#turn-tooltip'),BOOKS.filter(b=>b.cur.includes(id)));$('#turn-tabs').innerHTML=CURATIONS.map(x=>`<button class="${x.id===id?'active':''}" data-turn="${x.id}">${t(x.titleKey)}</button>`).join('');}
$('#turn-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-turn]');if(b)initHomeTurn(+b.dataset.turn);});

/* CURATION page */
function renderCurationPage(id){const wrap=$('#cur-detail');if(curScene){curScene.dispose();curScene=null;}if(!id){wrap.innerHTML='';return;}const c=CURATIONS.find(x=>x.id===+id);if(!c)return;const books=BOOKS.filter(b=>b.cur.includes(c.id));let stage='';
 if(c.type==='turn')stage=`<div class="turn-wrap"><canvas id="cur-turn-canvas"></canvas><div class="turn-tooltip" id="cur-turn-tooltip"></div></div>`;
 else if(c.type==='pop')stage=`<div class="popbook"><div class="pages"><div class="pg l"></div><div class="pg r"></div>${books.map((b,i)=>`<a href="#detail/${b.id}" class="stand" style="left:${6+i*(84/Math.max(books.length-1,1))}%;bottom:${20+(i%2)*35}%"><div class="book-cover" style="background:linear-gradient(150deg,${b.color[0]},${b.color[1]});animation-delay:${i*.12}s"><div class="t">${b.title}</div></div><small>${t('age_'+b.age)}</small></a>`).join('')}</div></div>`;
 else stage=`<div class="street"><div class="cloud" style="left:0;top:40px;width:160px;height:60px"></div><div class="cloud" style="left:-300px;top:110px;width:220px;height:80px;animation-delay:-12s"></div>${books.map((b,i)=>{const f=3+(b.id*7)%6;return `<a href="#detail/${b.id}" style="height:${f*9}%;background-color:${b.color[0]};animation-delay:${i*.1}s"><span>${b.title}</span></a>`;}).join('')}</div>`;
 wrap.innerHTML=`<span class="eyebrow">${t('type_'+c.type)}</span><h2 style="font-size:2rem;margin:.6rem 0 .2rem;font-weight:900">${t(c.titleKey)}</h2><p style="color:var(--ink2)">${t(c.descKey)}</p>${stage}<div class="cur-books">${books.map(b=>`<a href="#detail/${b.id}" class="res-card">${coverHTML(b)}<div><h4>${b.title}</h4><div class="meta">${LANG_NAMES[b.lang]} · ${t('age_'+b.age)}<br><span class="isbn">${b.isbn}</span></div><div class="price">${fmt(b.price)}</div><button class="mini-btn" data-add="${b.id}">${t('add')}</button></div></a>`).join('')}</div>`;
 if(c.type==='turn')curScene=makeTurntable($('#cur-turn-canvas'),$('#cur-turn-tooltip'),books);setTimeout(()=>wrap.scrollIntoView({behavior:'smooth'}),50);}

/* DETAIL */
function renderDetail(id){const b=byId(id)||BOOKS[0];const wrap=$('#detail');if(detailScene){detailScene.dispose();detailScene=null;}
 wrap.innerHTML=`<div><canvas id="detail-canvas"></canvas><p class="muted" style="text-align:center;margin-top:.6rem;font-family:var(--disp)">DRAG TO ROTATE · 3D PREVIEW</p></div><div class="detail-info"><span class="eyebrow">${t('age_'+b.age)} · ${LANG_NAMES[b.lang]} · ${b.country}</span><h2>${b.title}</h2><div class="orig">${b.orig}</div><div class="price">${fmt(b.price)}</div>${stockTag(b)}
 <div class="biblio"><div><span>${t('b_isbn')}</span><b class="isbn">${b.isbn}</b></div><div><span>${t('b_pub')}</span><b>${b.pub}</b></div><div><span>${t('b_lang')}</span><b>${LANG_NAMES[b.lang]}</b></div><div><span>${t('b_year')}</span><b>${b.year}</b></div><div><span>${t('b_country')}</span><b>${b.country}</b></div><div><span>${t('b_kdc')}</span><b>${b.kdc}</b></div><div><span>${t('b_age')}</span><b>${t('age_'+b.age)}</b></div><div><span>${t('b_pages')}</span><b>${b.pages}p</b></div></div><p class="desc">${b.desc||''}</p>
 <div class="detail-actions"><div class="qty"><button id="dq-m">−</button><input id="dq" value="1"><button id="dq-p">+</button></div><button class="btn btn-primary pop-btn" id="d-add"><span class="material-symbols-rounded">shopping_bag</span>${t('add')}</button></div></div>`;
 $('#dq-m').onclick=()=>$('#dq').value=Math.max(1,+$('#dq').value-1);$('#dq-p').onclick=()=>$('#dq').value=+$('#dq').value+1;$('#d-add').onclick=()=>addToCart(b.id,+$('#dq').value||1);
 const cv=$('#detail-canvas');const renderer=new THREE.WebGLRenderer({canvas:cv,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(38,1,.1,50);camera.position.set(0,.6,7);scene.add(new THREE.HemisphereLight(0xffffff,0xbfe9ff,.95));const dl=new THREE.DirectionalLight(0xffffff,.8);dl.position.set(3,6,5);dl.castShadow=true;scene.add(dl);const floor=new THREE.Mesh(new THREE.CylinderGeometry(2.4,2.4,.3,48),new THREE.MeshStandardMaterial({color:0xffffff}));floor.position.y=-1.9;floor.receiveShadow=true;scene.add(floor);
 const book=bookMesh(b,2.2,3.1,.42);book.castShadow=true;scene.add(book);
 let drag=false,lx=0,ly=0,ry=0,rx=0,vy=0;cv.onmousedown=e=>{drag=true;lx=e.clientX;ly=e.clientY;};addEventListener('mouseup',()=>drag=false);cv.onmousemove=e=>{if(!drag)return;vy=(e.clientX-lx)*.01;ry+=vy;rx+=(e.clientY-ly)*.006;lx=e.clientX;ly=e.clientY;};
 gsap.fromTo(book.scale,{x:.2,y:.2,z:.2},{x:1,y:1,z:1,duration:.9,ease:'elastic.out(1,.5)'});
 let alive=true;const clock=new THREE.Clock();(function anim(){if(!alive)return;requestAnimationFrame(anim);const t0=clock.getElapsedTime();camera.aspect=fitRenderer(renderer,cv);camera.updateProjectionMatrix();if(!drag){vy*=.95;ry+=vy+.006;}book.rotation.y=ry;book.rotation.x=rx*.5;book.position.y=Math.sin(t0*1.6)*.1;renderer.render(scene,camera);})();detailScene={dispose(){alive=false;renderer.dispose();}};}

function renderAll(){renderHomeCurations();renderNew();renderFilterChips();renderResults();renderCart();initHomeTurn(homeTurn?+($('#turn-tabs .active')||{dataset:{turn:1}}).dataset.turn:1);const h=(location.hash||'#home').slice(1).split('/');if(h[0]==='detail')renderDetail(h[1]);if(h[0]==='curation')renderCurationPage(h[1]);}
applyI18n();saveCart();route();
})();
